-- Starter question bank: 160 four-option questions, mixed difficulty.
--
-- Idempotent: re-running skips prompts that are already present, so this can be
-- replayed safely and topped up later without duplicating rows.

insert into public.questions (prompt, options, correct_index, category, difficulty)
select * from (values
  -- ---------------------------------------------------------------- geography
  ('What is the capital of Australia?', array['Sydney','Melbourne','Canberra','Perth'], 2, 'geography', 'medium'),
  ('Which river flows through Egypt?', array['Congo','Nile','Niger','Zambezi'], 1, 'geography', 'easy'),
  ('Which is the largest ocean on Earth?', array['Atlantic','Indian','Arctic','Pacific'], 3, 'geography', 'easy'),
  ('Which country has the most natural lakes?', array['Russia','Canada','Finland','Brazil'], 1, 'geography', 'medium'),
  ('What is the capital of Canada?', array['Toronto','Vancouver','Montreal','Ottawa'], 3, 'geography', 'medium'),
  ('Machu Picchu is located in which country?', array['Chile','Bolivia','Peru','Ecuador'], 2, 'geography', 'easy'),
  ('On which continent is the Sahara Desert?', array['Asia','Africa','Australia','South America'], 1, 'geography', 'easy'),
  ('Mount Everest sits on the border of Nepal and which other country?', array['India','China','Bhutan','Pakistan'], 1, 'geography', 'medium'),
  ('What is the capital of Japan?', array['Osaka','Kyoto','Tokyo','Nagoya'], 2, 'geography', 'easy'),
  ('The Grand Canyon is in which US state?', array['Nevada','Utah','Colorado','Arizona'], 3, 'geography', 'medium'),
  ('What is the smallest country in the world by area?', array['Monaco','Vatican City','San Marino','Liechtenstein'], 1, 'geography', 'easy'),
  ('Which capital city does the Danube NOT flow through?', array['Vienna','Budapest','Prague','Belgrade'], 2, 'geography', 'hard'),
  ('What is the capital of Brazil?', array['Rio de Janeiro','Sao Paulo','Brasilia','Salvador'], 2, 'geography', 'medium'),
  ('What is the capital of Iceland?', array['Reykjavik','Oslo','Helsinki','Bergen'], 0, 'geography', 'medium'),
  ('Which is the driest continent on Earth?', array['Africa','Australia','Antarctica','Asia'], 2, 'geography', 'hard'),
  ('What is the capital of Spain?', array['Barcelona','Seville','Valencia','Madrid'], 3, 'geography', 'easy'),
  ('Greenland is an autonomous territory of which country?', array['Norway','Denmark','Iceland','Sweden'], 1, 'geography', 'medium'),
  ('What is the largest hot desert in the world?', array['Gobi','Kalahari','Sahara','Arabian'], 2, 'geography', 'easy'),
  ('Which country is both in Europe and Asia and has Istanbul as its largest city?', array['Greece','Turkey','Georgia','Bulgaria'], 1, 'geography', 'easy'),
  ('Which US state is the largest by area?', array['Texas','California','Alaska','Montana'], 2, 'geography', 'medium'),

  -- ------------------------------------------------------------------ science
  ('What is the chemical symbol for gold?', array['Go','Au','Ag','Gd'], 1, 'science', 'easy'),
  ('How many bones are in the adult human body?', array['186','206','226','246'], 1, 'science', 'medium'),
  ('Which planet is known as the Red Planet?', array['Venus','Jupiter','Mars','Mercury'], 2, 'science', 'easy'),
  ('Which gas do plants absorb from the air for photosynthesis?', array['Oxygen','Nitrogen','Carbon dioxide','Hydrogen'], 2, 'science', 'easy'),
  ('Roughly how fast does light travel in a vacuum?', array['300,000 km/s','30,000 km/s','3,000,000 km/s','300 km/s'], 0, 'science', 'medium'),
  ('Which is the largest planet in our solar system?', array['Saturn','Jupiter','Neptune','Uranus'], 1, 'science', 'easy'),
  ('Which organelle is known as the powerhouse of the cell?', array['Nucleus','Ribosome','Mitochondria','Golgi body'], 2, 'science', 'easy'),
  ('How many chambers does the human heart have?', array['2','3','4','5'], 2, 'science', 'easy'),
  ('What is the most abundant gas in Earth''s atmosphere?', array['Oxygen','Nitrogen','Argon','Carbon dioxide'], 1, 'science', 'medium'),
  ('What is the chemical symbol for iron?', array['Ir','In','Fe','Fr'], 2, 'science', 'easy'),
  ('What is the hardest naturally occurring substance?', array['Quartz','Diamond','Titanium','Obsidian'], 1, 'science', 'easy'),
  ('How many planets are in our solar system?', array['7','8','9','10'], 1, 'science', 'easy'),
  ('What does DNA stand for?', array['Deoxyribonucleic acid','Dinucleic acid','Deoxyribose nucleus','Double nucleic acid'], 0, 'science', 'medium'),
  ('Which vitamin does the human body produce from sunlight?', array['Vitamin A','Vitamin B12','Vitamin C','Vitamin D'], 3, 'science', 'easy'),
  ('At sea level, water boils at what temperature in Celsius?', array['90','100','110','120'], 1, 'science', 'easy'),
  ('Which blood type is known as the universal donor?', array['AB positive','O negative','A negative','B positive'], 1, 'science', 'medium'),
  ('What is the scientific study of earthquakes called?', array['Geology','Seismology','Volcanology','Meteorology'], 1, 'science', 'medium'),
  ('What is the atomic number of hydrogen?', array['0','1','2','3'], 1, 'science', 'easy'),
  ('Which part of the brain controls balance and coordination?', array['Cerebrum','Cerebellum','Medulla','Hypothalamus'], 1, 'science', 'hard'),
  ('What is the speed unit "Mach 1" approximately equal to?', array['The speed of sound','The speed of light','1000 km/h','Escape velocity'], 0, 'science', 'medium'),

  -- -------------------------------------------------------------------- music
  ('Who is known as the King of Pop?', array['Elvis Presley','Michael Jackson','Prince','James Brown'], 1, 'music', 'easy'),
  ('Which band released "Bohemian Rhapsody"?', array['The Who','Led Zeppelin','Queen','Pink Floyd'], 2, 'music', 'easy'),
  ('How many strings does a standard guitar have?', array['4','5','6','7'], 2, 'music', 'easy'),
  ('Who sang "Like a Rolling Stone"?', array['Bob Dylan','Neil Young','Bruce Springsteen','Johnny Cash'], 0, 'music', 'medium'),
  ('Which Beatle was shot and killed in 1980?', array['Paul McCartney','George Harrison','John Lennon','Ringo Starr'], 2, 'music', 'easy'),
  ('Who recorded the song "Rolling in the Deep"?', array['Amy Winehouse','Adele','Duffy','Florence Welch'], 1, 'music', 'easy'),
  ('Which instrument was Louis Armstrong famous for playing?', array['Saxophone','Piano','Trumpet','Clarinet'], 2, 'music', 'medium'),
  ('Who composed "The Four Seasons"?', array['Bach','Mozart','Vivaldi','Handel'], 2, 'music', 'medium'),
  ('What is the best-selling album of all time?', array['Back in Black','Thriller','The Dark Side of the Moon','Rumours'], 1, 'music', 'medium'),
  ('Who was the lead singer of Nirvana?', array['Eddie Vedder','Kurt Cobain','Chris Cornell','Layne Staley'], 1, 'music', 'easy'),
  ('Who released the song "Shape of You"?', array['Ed Sheeran','Sam Smith','Justin Bieber','Shawn Mendes'], 0, 'music', 'easy'),
  ('How many keys does a standard full-size piano have?', array['76','82','88','92'], 2, 'music', 'medium'),
  ('Which famous composer continued composing after going deaf?', array['Chopin','Beethoven','Schubert','Liszt'], 1, 'music', 'easy'),
  ('Which rapper performs as "Slim Shady"?', array['Dr. Dre','Eminem','Jay-Z','Snoop Dogg'], 1, 'music', 'easy'),
  ('Which country was the band ABBA from?', array['Norway','Denmark','Sweden','Finland'], 2, 'music', 'easy'),
  ('Bob Marley is most associated with which genre?', array['Ska','Reggae','Calypso','Soul'], 1, 'music', 'easy'),
  ('Who recorded the album "Purple Rain"?', array['Prince','Rick James','Marvin Gaye','Stevie Wonder'], 0, 'music', 'medium'),
  ('Which band released "Wonderwall"?', array['Blur','Oasis','Pulp','The Verve'], 1, 'music', 'easy'),
  ('How many musicians are in a string quartet?', array['3','4','5','6'], 1, 'music', 'easy'),
  ('Which band released the album "Nevermind" with a baby underwater on the cover?', array['Pearl Jam','Nirvana','Soundgarden','Alice in Chains'], 1, 'music', 'medium'),

  -- --------------------------------------------------------------------- film
  ('Who directed the 1975 film "Jaws"?', array['George Lucas','Steven Spielberg','Martin Scorsese','Francis Ford Coppola'], 1, 'film', 'easy'),
  ('Which film features the line "I''ll be back"?', array['Predator','The Terminator','RoboCop','Total Recall'], 1, 'film', 'easy'),
  ('Who played Jack Dawson in "Titanic"?', array['Brad Pitt','Matt Damon','Leonardo DiCaprio','Johnny Depp'], 2, 'film', 'easy'),
  ('Which studio produced "Toy Story"?', array['DreamWorks','Pixar','Illumination','Blue Sky'], 1, 'film', 'easy'),
  ('"Winter is coming" is the motto of which TV house?', array['Lannister','Stark','Targaryen','Baratheon'], 1, 'film', 'easy'),
  ('Who played Harry Potter in the film series?', array['Rupert Grint','Daniel Radcliffe','Tom Felton','Eddie Redmayne'], 1, 'film', 'easy'),
  ('In "The Matrix", which colour pill does Neo take?', array['Blue','Red','Green','White'], 1, 'film', 'easy'),
  ('Who directed "Pulp Fiction"?', array['Quentin Tarantino','Robert Rodriguez','Guy Ritchie','David Fincher'], 0, 'film', 'easy'),
  ('Which hobbit carries the One Ring to Mordor?', array['Sam','Merry','Frodo','Pippin'], 2, 'film', 'easy'),
  ('Which animated film features a lion cub named Simba?', array['Madagascar','The Lion King','Tarzan','The Jungle Book'], 1, 'film', 'easy'),
  ('Which actor played Iron Man in the Marvel films?', array['Chris Evans','Robert Downey Jr.','Mark Ruffalo','Chris Hemsworth'], 1, 'film', 'easy'),
  ('"Here''s Johnny!" is a famous line from which film?', array['Psycho','The Shining','Misery','The Exorcist'], 1, 'film', 'medium'),
  ('In "Friends", what is the name of the coffee house?', array['Central Perk','Java Joe''s','The Grind','Cafe Nervosa'], 0, 'film', 'easy'),
  ('Which film won the Academy Award for Best Picture in 2020?', array['1917','Joker','Parasite','Once Upon a Time in Hollywood'], 2, 'film', 'medium'),
  ('What is the name of Batman''s butler?', array['Jarvis','Alfred','Reginald','Bruce'], 1, 'film', 'easy'),
  ('In "Star Wars", who is revealed to be Luke Skywalker''s father?', array['Obi-Wan Kenobi','Emperor Palpatine','Darth Vader','Han Solo'], 2, 'film', 'easy'),
  ('Which TV series follows chemistry teacher Walter White?', array['Better Call Saul','Breaking Bad','Ozark','The Wire'], 1, 'film', 'easy'),
  ('Who directed "Inception"?', array['Christopher Nolan','Ridley Scott','Denis Villeneuve','Alfonso Cuaron'], 0, 'film', 'easy'),
  ('In "The Godfather", what is the family name?', array['Soprano','Corleone','Gambino','Barzini'], 1, 'film', 'medium'),
  ('Which film features a character called Hannibal Lecter?', array['Se7en','The Silence of the Lambs','Zodiac','American Psycho'], 1, 'film', 'medium'),

  -- -------------------------------------------------------------------- sport
  ('How many players from one team are on a football (soccer) pitch at kickoff?', array['9','10','11','12'], 2, 'sport', 'easy'),
  ('How many years are there between Summer Olympic Games?', array['2','3','4','5'], 2, 'sport', 'easy'),
  ('Which country won the 2022 FIFA World Cup?', array['France','Brazil','Argentina','Croatia'], 2, 'sport', 'easy'),
  ('In tennis, what is a score of zero called?', array['Nil','Love','Duck','Blank'], 1, 'sport', 'easy'),
  ('How many points is a touchdown worth in American football?', array['3','6','7','8'], 1, 'sport', 'medium'),
  ('Which sport is played with a shuttlecock?', array['Squash','Badminton','Table tennis','Padel'], 1, 'sport', 'easy'),
  ('How many holes are played in a full round of golf?', array['9','12','18','21'], 2, 'sport', 'easy'),
  ('Sprinter Usain Bolt represents which country?', array['Trinidad and Tobago','Jamaica','Bahamas','Barbados'], 1, 'sport', 'easy'),
  ('Wimbledon is a major championship in which sport?', array['Golf','Tennis','Cricket','Rowing'], 1, 'sport', 'easy'),
  ('How many rings are on the Olympic flag?', array['4','5','6','7'], 1, 'sport', 'easy'),
  ('In basketball, how many points is a free throw worth?', array['1','2','3','4'], 0, 'sport', 'easy'),
  ('Which country hosted the 2016 Summer Olympics?', array['China','Brazil','United Kingdom','Japan'], 1, 'sport', 'medium'),
  ('Lewis Hamilton competes in which sport?', array['MotoGP','Formula 1','Rally','NASCAR'], 1, 'sport', 'easy'),
  ('A marathon is approximately how many kilometres?', array['32','38','42','48'], 2, 'sport', 'medium'),
  ('Michael Jordan is a legend of which sport?', array['Baseball','Basketball','American football','Golf'], 1, 'sport', 'easy'),
  ('How many players are on a cricket team?', array['9','10','11','12'], 2, 'sport', 'medium'),
  ('Which nation has won the most FIFA World Cups?', array['Germany','Italy','Brazil','Argentina'], 2, 'sport', 'medium'),
  ('In football, which colour card means a player is sent off?', array['Yellow','Red','Blue','Black'], 1, 'sport', 'easy'),
  ('What is the maximum score in a single game of ten-pin bowling?', array['200','250','300','360'], 2, 'sport', 'medium'),
  ('Which boxer was nicknamed "The Greatest"?', array['Mike Tyson','Muhammad Ali','Joe Frazier','Sugar Ray Leonard'], 1, 'sport', 'easy'),

  -- ------------------------------------------------------------------ history
  ('In which year did World War II end?', array['1943','1944','1945','1946'], 2, 'history', 'easy'),
  ('Who was the first person to walk on the Moon?', array['Buzz Aldrin','Neil Armstrong','Yuri Gagarin','Michael Collins'], 1, 'history', 'easy'),
  ('Which wall fell in 1989?', array['Hadrian''s Wall','The Berlin Wall','The Great Wall','The Western Wall'], 1, 'history', 'easy'),
  ('Who was the first President of the United States?', array['Thomas Jefferson','John Adams','George Washington','Benjamin Franklin'], 2, 'history', 'easy'),
  ('In which year did the Titanic sink?', array['1905','1912','1918','1923'], 1, 'history', 'easy'),
  ('Which empire built the Colosseum?', array['Greek','Roman','Ottoman','Byzantine'], 1, 'history', 'easy'),
  ('Who painted the Mona Lisa?', array['Michelangelo','Raphael','Leonardo da Vinci','Donatello'], 2, 'history', 'easy'),
  ('Which Egyptian queen was linked to both Julius Caesar and Mark Antony?', array['Nefertiti','Hatshepsut','Cleopatra','Ankhesenamun'], 2, 'history', 'medium'),
  ('In which year did World War I begin?', array['1912','1914','1916','1918'], 1, 'history', 'medium'),
  ('Who co-wrote "The Communist Manifesto" with Friedrich Engels?', array['Vladimir Lenin','Karl Marx','Leon Trotsky','Joseph Stalin'], 1, 'history', 'medium'),
  ('Which country gifted the Statue of Liberty to the United States?', array['Britain','France','Spain','Netherlands'], 1, 'history', 'medium'),
  ('At which battle was Napoleon finally defeated in 1815?', array['Austerlitz','Trafalgar','Waterloo','Borodino'], 2, 'history', 'medium'),
  ('Who discovered penicillin?', array['Louis Pasteur','Alexander Fleming','Robert Koch','Joseph Lister'], 1, 'history', 'medium'),
  ('In which year did the Chernobyl disaster occur?', array['1979','1986','1989','1991'], 1, 'history', 'medium'),
  ('Which civilisation built Machu Picchu?', array['Maya','Aztec','Inca','Olmec'], 2, 'history', 'medium'),
  ('Who was the British Prime Minister for most of World War II?', array['Neville Chamberlain','Winston Churchill','Clement Attlee','Anthony Eden'], 1, 'history', 'easy'),
  ('In which year was the Magna Carta sealed?', array['1066','1215','1314','1415'], 1, 'history', 'hard'),
  ('On which ship did Charles Darwin make his famous voyage?', array['HMS Victory','HMS Beagle','HMS Endeavour','HMS Discovery'], 1, 'history', 'medium'),
  ('In which year did the Soviet Union dissolve?', array['1989','1990','1991','1993'], 2, 'history', 'medium'),
  ('Which US President was assassinated in Dallas in 1963?', array['Franklin D. Roosevelt','John F. Kennedy','Abraham Lincoln','Lyndon B. Johnson'], 1, 'history', 'easy'),

  -- ------------------------------------------------------------- food & drink
  ('Pizza originated in which country?', array['Greece','Italy','France','Spain'], 1, 'food', 'easy'),
  ('What is the main ingredient in guacamole?', array['Courgette','Avocado','Cucumber','Pea'], 1, 'food', 'easy'),
  ('Which spirit is distilled from the agave plant?', array['Rum','Vodka','Tequila','Gin'], 2, 'food', 'easy'),
  ('Traditional Japanese sake is brewed from which grain?', array['Barley','Wheat','Rice','Millet'], 2, 'food', 'medium'),
  ('What is the main ingredient in hummus?', array['Lentils','Chickpeas','White beans','Broad beans'], 1, 'food', 'easy'),
  ('Wine is traditionally made by fermenting which fruit?', array['Apples','Pears','Grapes','Plums'], 2, 'food', 'easy'),
  ('Which herb is essential in a mojito?', array['Basil','Mint','Coriander','Thyme'], 1, 'food', 'easy'),
  ('Which cheese traditionally tops a Margherita pizza?', array['Cheddar','Mozzarella','Parmesan','Gouda'], 1, 'food', 'easy'),
  ('Guinness is what style of beer?', array['Lager','Pilsner','Stout','Wheat beer'], 2, 'food', 'easy'),
  ('Which country produces the most coffee in the world?', array['Colombia','Vietnam','Brazil','Ethiopia'], 2, 'food', 'medium'),
  ('Marzipan is made primarily from which nut?', array['Hazelnut','Almond','Walnut','Cashew'], 1, 'food', 'medium'),
  ('Which spirit forms the base of a mojito?', array['Rum','Vodka','Whisky','Brandy'], 0, 'food', 'easy'),
  ('In cooking, what does "al dente" describe?', array['Heavily salted','Cooked firm to the bite','Served cold','Slow roasted'], 1, 'food', 'medium'),
  ('Which vegetable is notorious for making people cry when chopped?', array['Garlic','Onion','Leek','Shallot'], 1, 'food', 'easy'),
  ('Which spice gives Hungarian goulash its characteristic colour and flavour?', array['Cumin','Paprika','Turmeric','Saffron'], 1, 'food', 'easy'),
  ('Champagne comes from a region of which country?', array['Italy','Spain','France','Portugal'], 2, 'food', 'easy'),
  ('Cider is made by fermenting which fruit?', array['Pears','Apples','Cherries','Berries'], 1, 'food', 'easy'),
  ('Tofu is made from which plant?', array['Chickpeas','Soybeans','Lentils','Peanuts'], 1, 'food', 'easy'),
  ('Which is the most expensive spice in the world by weight?', array['Vanilla','Cardamom','Saffron','Cinnamon'], 2, 'food', 'medium'),
  ('A classic Negroni contains gin, vermouth and what else?', array['Aperol','Campari','Cynar','Amaretto'], 1, 'food', 'hard'),

  -- ------------------------------------------------------------------ general
  ('How many days are in a leap year?', array['364','365','366','367'], 2, 'general', 'easy'),
  ('What is the currency of Japan?', array['Won','Yuan','Yen','Baht'], 2, 'general', 'easy'),
  ('How many letters are in the English alphabet?', array['24','25','26','27'], 2, 'general', 'easy'),
  ('What is the largest mammal on Earth?', array['African elephant','Blue whale','Giraffe','Orca'], 1, 'general', 'easy'),
  ('How many sides does a hexagon have?', array['5','6','7','8'], 1, 'general', 'easy'),
  ('Mixing blue and yellow paint produces which colour?', array['Purple','Orange','Green','Brown'], 2, 'general', 'easy'),
  ('How many minutes are there in a full day?', array['1200','1440','1600','1800'], 1, 'general', 'medium'),
  ('What is the tallest living animal?', array['Elephant','Giraffe','Ostrich','Camel'], 1, 'general', 'easy'),
  ('Which planet is closest to the Sun?', array['Venus','Mercury','Earth','Mars'], 1, 'general', 'easy'),
  ('How many degrees are in a full circle?', array['180','270','360','400'], 2, 'general', 'easy'),
  ('What is the fastest land animal?', array['Lion','Cheetah','Pronghorn','Greyhound'], 1, 'general', 'easy'),
  ('How many continents are there?', array['5','6','7','8'], 2, 'general', 'easy'),
  ('What do bees produce?', array['Silk','Honey','Wax only','Nectar'], 1, 'general', 'easy'),
  ('What is the Roman numeral for 50?', array['X','L','C','D'], 1, 'general', 'medium'),
  ('How many squares are on a standard chessboard?', array['36','49','64','81'], 2, 'general', 'easy'),
  ('What is the largest organ of the human body?', array['Liver','Skin','Lungs','Brain'], 1, 'general', 'medium'),
  ('How many hearts does an octopus have?', array['1','2','3','4'], 2, 'general', 'hard'),
  ('Which is the only mammal capable of true sustained flight?', array['Flying squirrel','Bat','Colugo','Sugar glider'], 1, 'general', 'medium'),
  ('How many colours are traditionally listed in a rainbow?', array['5','6','7','8'], 2, 'general', 'easy'),
  ('What is the currency used across most of the European Union?', array['Franc','Euro','Mark','Krone'], 1, 'general', 'easy')
) as q(prompt, options, correct_index, category, difficulty)
where not exists (
  select 1 from public.questions existing where existing.prompt = q.prompt
);
