insert into public.questions (prompt, options, correct_index, category, difficulty)
select prompt, options, correct_index, 'Celebrities', difficulty
from (values
  ('What is Lady Gaga''s real name?', array['Stefani Germanotta','Katheryn Hudson','Alecia Moore','Robyn Fenty'], 0, 'medium'),
  ('What was Elton John born as?', array['Reginald Dwight','David Jones','Gordon Sumner','Paul Hewson'], 0, 'hard'),
  ('Which actor is nicknamed "The Rock"?', array['Vin Diesel','Dwayne Johnson','John Cena','Jason Statham'], 1, 'easy'),
  ('What was Freddie Mercury''s birth name?', array['Farrokh Bulsara','Aziz Rahman','Cyrus Mistry','Rajesh Patel'], 0, 'hard'),
  ('Which artist released the visual album "Lemonade"?', array['Rihanna','Beyonce','Alicia Keys','Solange'], 1, 'medium'),
  ('What is Bruno Mars'' real first name?', array['Peter','Mark','Antonio','Julio'], 0, 'hard'),
  ('Who played Hermione Granger in the Harry Potter films?', array['Emma Stone','Emma Watson','Emma Roberts','Emma Thompson'], 1, 'easy'),
  ('What is Snoop Dogg''s real name?', array['Calvin Broadus','Andre Young','Marshall Mathers','O''Shea Jackson'], 0, 'medium'),
  ('What nationality is Hugh Jackman?', array['British','American','Australian','Canadian'], 2, 'medium'),
  ('Who played Captain Jack Sparrow?', array['Orlando Bloom','Johnny Depp','Geoffrey Rush','Jack Davenport'], 1, 'easy'),
  ('Bono is the frontman of which band?', array['Coldplay','U2','The Killers','Snow Patrol'], 1, 'easy'),
  ('Which island nation is Rihanna from?', array['Jamaica','Barbados','Trinidad and Tobago','Guyana'], 1, 'medium'),
  ('What were Marilyn Monroe''s real first names?', array['Norma Jeane','Betty Jean','Mary Jane','Nora Jane'], 0, 'hard'),
  ('Who voices Buzz Lightyear in the Toy Story films?', array['Tom Hanks','Tim Allen','Tom Selleck','Billy Crystal'], 1, 'medium'),
  ('Who founded SpaceX?', array['Jeff Bezos','Elon Musk','Peter Thiel','Larry Page'], 1, 'easy'),
  ('What nationality is Cristiano Ronaldo?', array['Spanish','Brazilian','Portuguese','Argentine'], 2, 'easy'),
  ('Who created and starred in "Fleabag"?', array['Olivia Colman','Phoebe Waller-Bridge','Jodie Comer','Sian Clifford'], 1, 'medium'),
  ('What is Katy Perry''s real surname?', array['Hudson','Perry','Moore','Fenty'], 0, 'hard'),
  ('Who wrote and originally starred in the musical "Hamilton"?', array['Lin-Manuel Miranda','Leslie Odom Jr.','Daveed Diggs','Christopher Jackson'], 0, 'medium'),
  ('Which British chef founded the Fifteen restaurant?', array['Gordon Ramsay','Jamie Oliver','Heston Blumenthal','Marco Pierre White'], 1, 'medium'),
  ('Who played Sherlock Holmes in the BBC series "Sherlock"?', array['Martin Freeman','Benedict Cumberbatch','Rupert Graves','Andrew Scott'], 1, 'easy'),
  ('Musician Stevie Wonder is famously what?', array['Deaf','Blind','Mute','Colour-blind'], 1, 'easy'),
  ('Who recorded the song "Bad Guy"?', array['Halsey','Billie Eilish','Lorde','Dua Lipa'], 1, 'easy'),
  ('What is Jay-Z''s real name?', array['Shawn Carter','Sean Combs','Curtis Jackson','Christopher Wallace'], 0, 'medium'),
  ('Who won the Best Actress Oscar for "La La Land"?', array['Natalie Portman','Emma Stone','Isabelle Huppert','Meryl Streep'], 1, 'medium'),
  ('David Beckham made his name in which sport?', array['Rugby','Cricket','Football','Tennis'], 2, 'easy'),
  ('Who played the Joker in the 2019 film "Joker"?', array['Jared Leto','Joaquin Phoenix','Heath Ledger','Jack Nicholson'], 1, 'easy'),
  ('Heath Ledger won a posthumous Oscar for playing whom?', array['The Joker','Ennis Del Mar','Ned Kelly','Patrick Verona'], 0, 'medium'),
  ('In which city was Keanu Reeves born?', array['Toronto','Beirut','Honolulu','Sydney'], 1, 'hard'),
  ('Which musician is known as "The Boss"?', array['Bob Seger','Bruce Springsteen','Tom Petty','John Mellencamp'], 1, 'medium'),
  ('Which reality series made the Kardashian family famous?', array['The Simple Life','Keeping Up with the Kardashians','The Hills','Laguna Beach'], 1, 'easy'),
  ('Who played Neo in "The Matrix"?', array['Laurence Fishburne','Keanu Reeves','Hugo Weaving','Joe Pantoliano'], 1, 'easy'),
  ('Who co-founded Facebook and became its CEO?', array['Jack Dorsey','Mark Zuckerberg','Evan Spiegel','Kevin Systrom'], 1, 'easy'),
  ('Who played Black Widow in the Marvel films?', array['Elizabeth Olsen','Scarlett Johansson','Brie Larson','Florence Pugh'], 1, 'easy'),
  ('What was Elvis Presley''s middle name?', array['Aaron','Andrew','Alan','Arthur'], 0, 'hard'),
  ('Which musician created the alter ego Ziggy Stardust?', array['David Bowie','Marc Bolan','Bryan Ferry','Iggy Pop'], 0, 'medium'),
  ('Who was the first actor to play James Bond on film?', array['Roger Moore','Sean Connery','George Lazenby','Timothy Dalton'], 1, 'medium'),
  ('Which actress played M in the Bond films from 1995?', array['Helen Mirren','Judi Dench','Maggie Smith','Julie Walters'], 1, 'medium'),
  ('Who played Rose in "Titanic"?', array['Kate Winslet','Gwyneth Paltrow','Cate Blanchett','Nicole Kidman'], 0, 'easy'),
  ('Which singer wore a dress made of raw meat to an awards show?', array['Madonna','Lady Gaga','Cher','Bjork'], 1, 'medium'),
  ('What is Madonna''s surname?', array['Ciccone','Rossi','Bellini','Moretti'], 0, 'hard'),
  ('What is the YouTuber PewDiePie''s real name?', array['Felix Kjellberg','Olof Persson','Erik Lund','Anders Berg'], 0, 'hard'),
  ('Who plays Thor in the Marvel films?', array['Chris Evans','Chris Hemsworth','Chris Pratt','Chris Pine'], 1, 'easy'),
  ('Which talk show host launched the OWN network?', array['Ellen DeGeneres','Oprah Winfrey','Tyra Banks','Rosie O''Donnell'], 1, 'medium'),
  ('What is Eminem''s real name?', array['Marshall Mathers','Calvin Broadus','Andre Young','Nasir Jones'], 0, 'easy'),
  ('Which knighted actor played Gandalf?', array['Ian McKellen','Patrick Stewart','Christopher Lee','Michael Gambon'], 0, 'easy'),
  ('Who played Daenerys Targaryen in "Game of Thrones"?', array['Emilia Clarke','Sophie Turner','Maisie Williams','Natalie Dormer'], 0, 'easy'),
  ('What nationality is Ed Sheeran?', array['Irish','English','Scottish','Welsh'], 1, 'easy'),
  ('Which guitarist is nicknamed "Slowhand"?', array['Jimmy Page','Eric Clapton','Jeff Beck','Keith Richards'], 1, 'hard'),
  ('Which country is the singer Shakira from?', array['Mexico','Colombia','Venezuela','Argentina'], 1, 'medium'),
  ('Which actor delivers the line "You talkin'' to me?" in "Taxi Driver"?', array['Al Pacino','Robert De Niro','Joe Pesci','Harvey Keitel'], 1, 'medium'),
  ('Who directed and starred in the 2018 version of "A Star Is Born"?', array['Bradley Cooper','Sam Elliott','Andrew Dice Clay','Ryan Gosling'], 0, 'medium'),
  ('Which comedian created the UK version of "The Office"?', array['Ricky Gervais','Steve Coogan','Simon Pegg','Matt Lucas'], 0, 'medium'),
  ('Who played Miranda Priestly in "The Devil Wears Prada"?', array['Meryl Streep','Glenn Close','Sigourney Weaver','Diane Keaton'], 0, 'easy'),
  ('Who is known as the King of Rock and Roll?', array['Chuck Berry','Elvis Presley','Little Richard','Jerry Lee Lewis'], 1, 'easy'),
  ('Which model created and hosted "America''s Next Top Model"?', array['Heidi Klum','Tyra Banks','Naomi Campbell','Cindy Crawford'], 1, 'medium'),
  ('Who played Tony Soprano?', array['James Gandolfini','Michael Imperioli','Steve Buscemi','Tony Sirico'], 0, 'medium'),
  ('Which city is the singer Adele from?', array['Manchester','London','Bristol','Liverpool'], 1, 'medium'),
  ('Who played the assassin Villanelle in "Killing Eve"?', array['Sandra Oh','Jodie Comer','Fiona Shaw','Phoebe Waller-Bridge'], 1, 'medium'),
  ('Which footballer is nicknamed "La Pulga", the Flea?', array['Neymar','Lionel Messi','Sergio Aguero','Luis Suarez'], 1, 'medium'),
  ('Who played Walter White in "Breaking Bad"?', array['Aaron Paul','Bryan Cranston','Bob Odenkirk','Giancarlo Esposito'], 1, 'easy'),
  ('Who sang "...Baby One More Time"?', array['Christina Aguilera','Britney Spears','Jessica Simpson','Mandy Moore'], 1, 'easy'),
  ('Which actor plays Deadpool?', array['Ryan Gosling','Ryan Reynolds','Chris Evans','Jake Gyllenhaal'], 1, 'easy'),
  ('Which fashion designer was murdered outside his Miami home in 1997?', array['Gianni Versace','Karl Lagerfeld','Yves Saint Laurent','Valentino'], 0, 'hard'),
  ('Which artist changed his stage name to an unpronounceable symbol in 1993?', array['Prince','Michael Jackson','Seal','Sting'], 0, 'medium'),
  ('Who played Mia Wallace in "Pulp Fiction"?', array['Uma Thurman','Rosanna Arquette','Maria de Medeiros','Amanda Plummer'], 0, 'medium'),
  ('Which comedian created and played Mr. Bean?', array['Rowan Atkinson','John Cleese','Hugh Laurie','Stephen Fry'], 0, 'easy'),
  ('Which singer''s surname is Fenty?', array['Rihanna','Beyonce','Ciara','Kelly Rowland'], 0, 'medium'),
  ('Which actor performed Gollum through motion capture?', array['Andy Serkis','Elijah Wood','Sean Astin','Dominic Monaghan'], 0, 'medium'),
  ('Who has hosted "The Late Show" since 2015?', array['Jimmy Kimmel','Stephen Colbert','Conan O''Brien','Seth Meyers'], 1, 'medium'),
  ('Who played Katniss Everdeen in "The Hunger Games"?', array['Shailene Woodley','Jennifer Lawrence','Emma Watson','Kristen Stewart'], 1, 'easy'),
  ('What is the singer Sting''s real name?', array['Gordon Sumner','Paul Hewson','David Evans','Reginald Dwight'], 0, 'hard'),
  ('Which actor plays Loki in the Marvel films?', array['Tom Hardy','Tom Hiddleston','Tom Holland','Tom Felton'], 1, 'easy'),
  ('Which chef runs the restaurant The Fat Duck?', array['Heston Blumenthal','Gordon Ramsay','Marco Pierre White','Rick Stein'], 0, 'hard'),
  ('Who sang "Someone Like You"?', array['Amy Winehouse','Adele','Sam Smith','Emeli Sande'], 1, 'easy'),
  ('Who played Indiana Jones?', array['Harrison Ford','Kurt Russell','Tom Selleck','Mel Gibson'], 0, 'easy'),
  ('Which actress is the daughter of Goldie Hawn?', array['Kate Hudson','Dakota Johnson','Rashida Jones','Zoe Kravitz'], 0, 'hard'),
  ('Which actor is the son of Kirk Douglas?', array['Michael Douglas','Jeff Bridges','Charlie Sheen','Colin Hanks'], 0, 'medium'),
  ('Who was the lead singer of The Doors?', array['Jim Morrison','Lou Reed','Iggy Pop','Jim Croce'], 0, 'medium'),
  ('Which supermodel is nicknamed "The Body"?', array['Elle Macpherson','Claudia Schiffer','Linda Evangelista','Christy Turlington'], 0, 'hard'),
  ('Who played Hannibal Lecter in "The Silence of the Lambs"?', array['Anthony Hopkins','Mads Mikkelsen','Brian Cox','Gary Oldman'], 0, 'easy'),
  ('Who recorded "Rocket Man"?', array['Elton John','Billy Joel','David Bowie','Rod Stewart'], 0, 'easy'),
  ('Who won the Best Actress Oscar for "Black Swan"?', array['Mila Kunis','Natalie Portman','Winona Ryder','Barbara Hershey'], 1, 'medium'),
  ('Which broadcaster narrated the BBC series "Planet Earth"?', array['David Attenborough','Chris Packham','Steve Backshall','Bill Oddie'], 0, 'easy'),
  ('Which rapper''s real name is Aubrey Graham?', array['Drake','Kanye West','Travis Scott','Lil Wayne'], 0, 'medium'),
  ('What is The Weeknd''s real name?', array['Abel Tesfaye','Aubrey Graham','Jacques Webster','Sean Anderson'], 0, 'hard'),
  ('Who played Jack Torrance in "The Shining"?', array['Jack Nicholson','Robert Duvall','Dennis Hopper','Christopher Walken'], 0, 'easy'),
  ('Justin Timberlake first found fame in which group?', array['Backstreet Boys','NSYNC','Boyz II Men','98 Degrees'], 1, 'medium'),
  ('Who sang "Let It Go" as Elsa in "Frozen"?', array['Kristen Bell','Idina Menzel','Anna Kendrick','Amy Adams'], 1, 'medium'),
  ('Which tennis player is known as "Rafa"?', array['Roger Federer','Rafael Nadal','Novak Djokovic','Andy Murray'], 1, 'easy'),
  ('Who hosted "The Daily Show" from 1999 to 2015?', array['Trevor Noah','Jon Stewart','Craig Kilborn','Stephen Colbert'], 1, 'medium'),
  ('Who played Carrie Bradshaw in "Sex and the City"?', array['Kim Cattrall','Sarah Jessica Parker','Cynthia Nixon','Kristin Davis'], 1, 'easy'),
  ('Which performer popularised the "moonwalk"?', array['James Brown','Michael Jackson','Usher','Chris Brown'], 1, 'easy'),
  ('Which actor played Wolverine in the X-Men films?', array['Ryan Reynolds','Hugh Jackman','Liev Schreiber','Patrick Stewart'], 1, 'easy'),
  ('Which singer is known as the Queen of Pop?', array['Cher','Madonna','Whitney Houston','Janet Jackson'], 1, 'easy'),
  ('Who played Forrest Gump?', array['Tom Cruise','Tom Hanks','Kevin Costner','Robin Williams'], 1, 'easy'),
  ('Which actress starred as Éowyn in "The Lord of the Rings"?', array['Miranda Otto','Liv Tyler','Cate Blanchett','Naomi Watts'], 0, 'hard'),
  ('Which musician married Yoko Ono?', array['Paul McCartney','John Lennon','George Harrison','Ringo Starr'], 1, 'easy'),
  ('Which actor played Maximus in "Gladiator"?', array['Russell Crowe','Joaquin Phoenix','Richard Harris','Djimon Hounsou'], 0, 'easy'),
  ('Which singer is famous for the song "Purple Rain"?', array['Prince','Rick James','Marvin Gaye','Stevie Wonder'], 0, 'medium'),
  ('Which comedian and actor starred in "Mrs. Doubtfire"?', array['Steve Martin','Robin Williams','Eddie Murphy','Billy Crystal'], 1, 'easy')
) as q(prompt, options, correct_index, difficulty)
where not exists (
  select 1 from public.questions existing where existing.prompt = q.prompt
);
