insert into public.questions (prompt, options, correct_index, category, difficulty)
select prompt, options, correct_index, 'Sport', difficulty
from (values
  ('How many minutes long is a standard football match, not including stoppage time?', array['60','80','90','120'], 2, 'easy'),
  ('What is the maximum number of substitutions a football team can make in a normal league match under current rules?', array['3','4','5','6'], 2, 'medium'),
  ('Which club has won the most UEFA Champions League titles?', array['Barcelona','Real Madrid','AC Milan','Bayern Munich'], 1, 'medium'),
  ('Which country hosted the first FIFA World Cup in 1930?', array['Brazil','Uruguay','Italy','France'], 1, 'hard'),
  ('A hat-trick in football means a player scored how many goals in a match?', array['2','3','4','5'], 1, 'easy'),
  ('Pele played international football for which country?', array['Argentina','Brazil','Portugal','Spain'], 1, 'easy'),
  ('Diego Maradona''s "Hand of God" goal in 1986 was scored against which team?', array['England','Germany','Italy','France'], 0, 'medium'),
  ('Which English football club is nicknamed "The Red Devils"?', array['Liverpool','Manchester United','Arsenal','Chelsea'], 1, 'easy'),
  ('Which division sits directly below the Premier League in English football?', array['Championship','League One','League Two','National League'], 0, 'medium'),
  ('Which country won the UEFA European Championship in 2021 (Euro 2020)?', array['England','Italy','Spain','Germany'], 1, 'medium'),
  ('How many players from each team are on the court at once in basketball?', array['4','5','6','7'], 1, 'easy'),
  ('Which NBA franchise has won the most championships?', array['Los Angeles Lakers','Boston Celtics','Chicago Bulls','Golden State Warriors'], 1, 'medium'),
  ('How long is a standard NBA quarter?', array['10 minutes','12 minutes','15 minutes','20 minutes'], 1, 'medium'),
  ('Which basketball player is nicknamed "King James"?', array['Kobe Bryant','LeBron James','Kevin Durant','Stephen Curry'], 1, 'easy'),
  ('How many points is a successful shot from beyond the three-point line worth?', array['1','2','3','4'], 2, 'easy'),
  ('Basketball was invented by James Naismith, who was originally from which country?', array['USA','Canada','England','Scotland'], 1, 'hard'),
  ('In the NBA, how many personal fouls disqualify a player from a game?', array['4','5','6','7'], 2, 'medium'),
  ('How many Grand Slam tennis tournaments are held each year?', array['3','4','5','6'], 1, 'easy'),
  ('Which Grand Slam tennis tournament is played on clay courts?', array['Wimbledon','US Open','French Open','Australian Open'], 2, 'easy'),
  ('Which Grand Slam tennis tournament is held in Melbourne?', array['Australian Open','US Open','French Open','Wimbledon'], 0, 'easy'),
  ('In tennis, what is a score of 40-40 called?', array['Deuce','Love','Advantage','Break'], 0, 'easy'),
  ('As of 2024, which player holds the record for most men''s Grand Slam singles titles?', array['Roger Federer','Rafael Nadal','Novak Djokovic','Pete Sampras'], 2, 'medium'),
  ('Which country does tennis legend Serena Williams represent?', array['United States','Jamaica','United Kingdom','Canada'], 0, 'easy'),
  ('In tennis slang, what is it called when a player wins a set 6-0?', array['A bagel','A love set','A whitewash','A shutout'], 0, 'medium'),
  ('In golf, what is the term for finishing a hole one stroke under par?', array['Eagle','Birdie','Bogey','Par'], 1, 'easy'),
  ('In golf, what is the term for finishing a hole one stroke over par?', array['Eagle','Birdie','Bogey','Albatross'], 2, 'easy'),
  ('In golf, what is the term for finishing a hole two strokes under par?', array['Eagle','Birdie','Condor','Albatross'], 0, 'medium'),
  ('Which major golf championship is played annually at Augusta National?', array['The Masters','The Open Championship','The US Open','The PGA Championship'], 0, 'medium'),
  ('Which golfer holds the record for the most men''s major championships won?', array['Tiger Woods','Jack Nicklaus','Arnold Palmer','Gary Player'], 1, 'medium'),
  ('How many clubs is a golfer allowed to carry in their bag during a round?', array['10','12','14','16'], 2, 'medium'),
  ('In a standard world title boxing match, how many rounds are scheduled?', array['10','12','15','3'], 1, 'medium'),
  ('Which heavyweight boxer was known as "Iron Mike"?', array['Mike Tyson','George Foreman','Sugar Ray Leonard','Evander Holyfield'], 0, 'easy'),
  ('What is the heaviest weight division in professional boxing called?', array['Middleweight','Heavyweight','Cruiserweight','Welterweight'], 1, 'easy'),
  ('Muhammad Ali''s 1974 fight against George Foreman in Zaire is known as?', array['The Thrilla in Manila','The Rumble in the Jungle','The Sunshine Showdown','The Fight of the Century'], 1, 'medium'),
  ('In boxing, what is it called when a fighter wins because their opponent cannot continue?', array['A knockout','A submission','A pinfall','A forfeit'], 0, 'easy'),
  ('How often are the Winter Olympic Games held?', array['Every 2 years','Every 4 years','Every 5 years','Every 6 years'], 1, 'easy'),
  ('Which city hosted the 2020 Summer Olympics, actually held in 2021?', array['Tokyo','Beijing','Paris','London'], 0, 'easy'),
  ('Which city will host the 2028 Summer Olympics?', array['Paris','Los Angeles','Brisbane','Rome'], 1, 'medium'),
  ('What is the standard length of an Olympic-size swimming pool?', array['25 metres','50 metres','100 metres','33 metres'], 1, 'medium'),
  ('How many events make up a men''s decathlon?', array['7','8','10','12'], 2, 'easy'),
  ('How many events make up a women''s heptathlon?', array['5','6','7','8'], 2, 'medium'),
  ('Jesse Owens famously won four gold medals at which Olympic Games?', array['1932 Los Angeles','1936 Berlin','1948 London','1952 Helsinki'], 1, 'hard'),
  ('Which swimmer holds the record for the most Olympic gold medals ever won?', array['Mark Spitz','Michael Phelps','Ryan Lochte','Katie Ledecky'], 1, 'easy'),
  ('Which country has won the most Olympic gold medals of all time?', array['Soviet Union','United States','China','Great Britain'], 1, 'medium'),
  ('What is a score of zero for a batsman called in cricket?', array['A duck','A goose','A blank','A zero'], 0, 'easy'),
  ('What is it called when a bowler takes three wickets on three consecutive balls in cricket?', array['A triple','A hat-trick','A treble','A trio'], 1, 'medium'),
  ('Which country won the first Cricket World Cup in 1975?', array['England','Australia','West Indies','India'], 2, 'hard'),
  ('How many balls make up a standard over in cricket?', array['4','5','6','8'], 2, 'easy'),
  ('What is the longest and oldest format of international cricket called?', array['Test cricket','One Day cricket','T20 cricket','The Hundred'], 0, 'medium'),
  ('What is the three-stump structure defended by a batsman in cricket called?', array['A wicket','A crease','A gully','A silly point'], 0, 'medium'),
  ('England and Australia compete for which trophy in Test cricket?', array['The Ashes','The Wisden Cup','The Waterloo Cup','The Champions Trophy'], 0, 'medium'),
  ('How many points is a try worth in rugby union?', array['3','4','5','7'], 2, 'medium'),
  ('As of 2023, which country has won the most Rugby World Cups?', array['New Zealand','South Africa','Australia','England'], 1, 'medium'),
  ('How many players are on a rugby league team on the field, compared to union''s 15?', array['11','12','13','15'], 2, 'medium'),
  ('What shape is a rugby ball?', array['Round','Oval','Triangular','Square'], 1, 'easy'),
  ('How many World Championships did Michael Schumacher win in Formula 1?', array['5','6','7','8'], 2, 'medium'),
  ('The Monaco Grand Prix is held in which country?', array['Monaco','France','Italy','Switzerland'], 0, 'easy'),
  ('In Formula 1, what does a yellow flag signal to drivers?', array['The race has finished','Danger ahead - slow down','The pit lane is open','A new fastest lap'], 1, 'medium'),
  ('Which team holds the record for the most Formula 1 Constructors'' Championships?', array['Ferrari','McLaren','Mercedes','Williams'], 0, 'medium'),
  ('What is it called when an F1 car has its tyres changed and is refuelled during a race?', array['A pit stop','A tyre change','A service stop','A relay'], 0, 'easy'),
  ('Which swimming stroke is typically the fastest in competition?', array['Backstroke','Breaststroke','Butterfly','Freestyle'], 3, 'medium'),
  ('A "triple axel" is a jump performed in which sport?', array['Figure skating','Gymnastics','Diving','Alpine skiing'], 0, 'easy'),
  ('In luge, how does the athlete lie on the sled?', array['On their back, feet-first','On their front, head-first','Standing upright','Kneeling'], 0, 'medium'),
  ('Including the goaltender, how many players does an ice hockey team have on the ice per side?', array['5','6','7','8'], 1, 'medium'),
  ('How many innings are in a standard Major League Baseball game?', array['7','8','9','10'], 2, 'easy'),
  ('How many players from one team are on the field at once in baseball?', array['8','9','10','11'], 1, 'easy'),
  ('How many strikes result in a batter being called out in baseball?', array['2','3','4','5'], 1, 'easy'),
  ('What is it called when a batter hits a home run with the bases loaded, scoring four runs?', array['A grand slam','A home run derby','A triple play','A perfect game'], 0, 'medium'),
  ('How many players from one team are on the field at once in American football?', array['9','10','11','12'], 2, 'easy'),
  ('What is it called when a quarterback throws the ball into the ground to stop the clock?', array['A spike','A sack','A punt','A fumble'], 0, 'medium'),
  ('How many career Super Bowl wins does quarterback Tom Brady have?', array['5','6','7','8'], 2, 'medium'),
  ('In American football, what is a successful kick through the goalposts worth 3 points called?', array['A field goal','A touchdown','A safety','A two-point conversion'], 0, 'easy'),
  ('Which cycling race is nicknamed "Le Tour"?', array['Tour de France','Giro d''Italia','Vuelta a Espana','Paris-Roubaix'], 0, 'easy'),
  ('What colour jersey does the overall leader wear in the Tour de France?', array['Yellow','Green','Polka dot','White'], 0, 'easy'),
  ('In the Tour de France, what does the green jersey represent?', array['Best climber','Points classification','Best young rider','Overall leader'], 1, 'medium'),
  ('Which sport uses terms like "spare" and "strike"?', array['Ten-pin bowling','Darts','Snooker','Table tennis'], 0, 'easy'),
  ('In snooker, how many red balls are on the table at the start of a frame?', array['10','12','15','20'], 2, 'medium'),
  ('In darts, what is the highest score achievable with a single dart?', array['50','57','60','180'], 2, 'medium'),
  ('What is it called when a player finishes a leg of darts by reducing their score to exactly zero?', array['A finish','A bullseye','A maximum','A ton'], 0, 'medium'),
  ('Which trophy is awarded to the NHL playoff champion in ice hockey?', array['The Stanley Cup','The Vince Lombardi Trophy','The Commissioner''s Trophy','The Larry O''Brien Trophy'], 0, 'easy')
) as q(prompt, options, correct_index, difficulty)
where not exists (
  select 1 from public.questions existing where existing.prompt = q.prompt
);
