insert into public.questions (prompt, options, correct_index, category, difficulty)
select prompt, options, correct_index, 'Geography', difficulty
from (values
  ('What is the longest river in the world?', array['Amazon','Nile','Yangtze','Mississippi'], 1, 'medium'),
  ('Which is the largest country in the world by land area?', array['Canada','China','United States','Russia'], 3, 'easy'),
  ('Which is the smallest continent by land area?', array['Europe','Australia','Antarctica','South America'], 1, 'medium'),
  ('What is the capital of Germany?', array['Munich','Berlin','Frankfurt','Hamburg'], 1, 'easy'),
  ('What is the capital of Italy?', array['Milan','Naples','Rome','Venice'], 2, 'easy'),
  ('What is the capital of Russia?', array['St Petersburg','Moscow','Kiev','Minsk'], 1, 'easy'),
  ('What is the capital of China?', array['Shanghai','Hong Kong','Beijing','Guangzhou'], 2, 'easy'),
  ('What is the capital of India?', array['Mumbai','New Delhi','Bangalore','Kolkata'], 1, 'easy'),
  ('What is the capital of South Korea?', array['Busan','Seoul','Incheon','Daegu'], 1, 'easy'),
  ('What is the capital of Argentina?', array['Rio de Janeiro','Santiago','Buenos Aires','Montevideo'], 2, 'easy'),
  ('What is the capital of Mexico?', array['Guadalajara','Cancun','Mexico City','Monterrey'], 2, 'easy'),
  ('What is the capital of Egypt?', array['Alexandria','Cairo','Giza','Luxor'], 1, 'easy'),
  ('What is the capital of South Africa (the executive capital)?', array['Cape Town','Johannesburg','Pretoria','Durban'], 2, 'hard'),
  ('What is the capital of Kenya?', array['Nairobi','Mombasa','Kisumu','Nakuru'], 0, 'medium'),
  ('What is the capital of Norway?', array['Bergen','Oslo','Stavanger','Trondheim'], 1, 'medium'),
  ('What is the capital of Sweden?', array['Gothenburg','Stockholm','Malmo','Uppsala'], 1, 'easy'),
  ('What is the capital of Portugal?', array['Porto','Lisbon','Faro','Braga'], 1, 'easy'),
  ('What is the capital of Greece?', array['Thessaloniki','Athens','Patras','Heraklion'], 1, 'easy'),
  ('What is the capital of Poland?', array['Krakow','Warsaw','Gdansk','Wroclaw'], 1, 'easy'),
  ('What is the capital of the Netherlands?', array['Rotterdam','The Hague','Amsterdam','Utrecht'], 2, 'medium'),
  ('What is the capital of Switzerland?', array['Zurich','Geneva','Bern','Basel'], 2, 'medium'),
  ('What is the capital of Austria?', array['Salzburg','Vienna','Graz','Innsbruck'], 1, 'easy'),
  ('What is the capital of Ireland?', array['Cork','Belfast','Dublin','Galway'], 2, 'easy'),
  ('What is the capital of Thailand?', array['Bangkok','Chiang Mai','Phuket','Pattaya'], 0, 'easy'),
  ('What is the capital of Vietnam?', array['Ho Chi Minh City','Hanoi','Da Nang','Hue'], 1, 'medium'),
  ('What is the capital of Indonesia?', array['Jakarta','Bali','Surabaya','Bandung'], 0, 'medium'),
  ('What is the capital of the Philippines?', array['Cebu City','Manila','Davao','Quezon City'], 1, 'medium'),
  ('What is the capital of New Zealand?', array['Auckland','Christchurch','Wellington','Hamilton'], 2, 'medium'),
  ('What is the capital of Chile?', array['Valparaiso','Santiago','Concepcion','La Serena'], 1, 'easy'),
  ('What is the capital of Colombia?', array['Medellin','Bogota','Cali','Cartagena'], 1, 'medium'),
  ('What is the capital of Peru?', array['Cusco','Lima','Arequipa','Trujillo'], 1, 'easy'),
  ('What is the capital of Cuba?', array['Santiago de Cuba','Havana','Camaguey','Holguin'], 1, 'easy'),
  ('What is the capital of Morocco?', array['Casablanca','Rabat','Marrakesh','Fez'], 1, 'hard'),
  ('What is the capital of Nigeria?', array['Lagos','Abuja','Kano','Ibadan'], 1, 'hard'),
  ('What is the capital of Saudi Arabia?', array['Jeddah','Mecca','Riyadh','Medina'], 2, 'medium'),
  ('What is the capital of the United Arab Emirates?', array['Dubai','Abu Dhabi','Sharjah','Ajman'], 1, 'medium'),
  ('What is the capital of Israel, as recognised by most of the international community?', array['Jerusalem','Tel Aviv','Haifa','Eilat'], 1, 'hard'),
  ('Which African country was formerly known as Abyssinia?', array['Sudan','Ethiopia','Eritrea','Somalia'], 1, 'hard'),
  ('Which country is the largest by population?', array['United States','Indonesia','India','China'], 2, 'medium'),
  ('Which is the longest mountain range in the world?', array['Rocky Mountains','Andes','Himalayas','Alps'], 1, 'medium'),
  ('Which is the tallest mountain in Africa?', array['Mount Kenya','Mount Kilimanjaro','Table Mountain','Atlas Mountains'], 1, 'easy'),
  ('Which sea lies between Europe and Africa?', array['Red Sea','Black Sea','Mediterranean Sea','Caspian Sea'], 2, 'easy'),
  ('What is the largest island in the world?', array['Madagascar','Borneo','Greenland','New Guinea'], 2, 'medium'),
  ('Which strait separates Europe from Africa at its narrowest point?', array['Strait of Hormuz','Strait of Gibraltar','Bosphorus Strait','Bering Strait'], 1, 'medium'),
  ('Which US state is known as the Sunshine State?', array['California','Florida','Arizona','Texas'], 1, 'easy'),
  ('Which city is known as the Big Apple?', array['Los Angeles','Chicago','New York City','Boston'], 2, 'easy'),
  ('Which country has the most time zones?', array['Russia','United States','China','France'], 3, 'hard'),
  ('Which country is entirely surrounded by South Africa?', array['Eswatini','Lesotho','Botswana','Zimbabwe'], 1, 'medium'),
  ('Which two countries share the longest international border in the world?', array['USA and Canada','Russia and China','India and China','Chile and Argentina'], 0, 'medium'),
  ('Which African country has three capital cities?', array['Kenya','South Africa','Nigeria','Tanzania'], 1, 'hard'),
  ('What is the driest place on Earth?', array['Sahara Desert','Death Valley','Atacama Desert','Gobi Desert'], 2, 'hard'),
  ('Which country has the most active volcanoes?', array['Japan','Indonesia','United States','Philippines'], 1, 'hard'),
  ('Which river flows through Paris?', array['Rhine','Seine','Loire','Rhone'], 1, 'easy'),
  ('Which river flows through London?', array['Severn','Avon','Thames','Mersey'], 2, 'easy'),
  ('Which country does the island of Sicily belong to?', array['Greece','Italy','Malta','Tunisia'], 1, 'easy'),
  ('Which country has the most pyramids?', array['Egypt','Mexico','Sudan','Peru'], 2, 'hard'),
  ('Which is the largest lake in Africa?', array['Lake Tanganyika','Lake Victoria','Lake Malawi','Lake Chad'], 1, 'medium'),
  ('Which is the deepest lake in the world?', array['Lake Superior','Lake Baikal','Caspian Sea','Lake Tanganyika'], 1, 'hard'),
  ('Which mountain range separates Europe from Asia?', array['Alps','Carpathians','Ural Mountains','Caucasus'], 2, 'medium'),
  ('Which country is home to the ancient city of Petra?', array['Egypt','Jordan','Syria','Iraq'], 1, 'medium'),
  ('Which South American country is named after the explorer Amerigo Vespucci?', array['Colombia','Venezuela','Bolivia','Ecuador'], 1, 'hard'),
  ('Which European country is made up of over 17,000 islands?', array['Greece','Norway','Sweden','Denmark'], 1, 'hard'),
  ('Which country is known as the Land of the Rising Sun?', array['China','Thailand','Japan','South Korea'], 2, 'easy'),
  ('Which country is known as the Land Down Under?', array['New Zealand','Australia','South Africa','Argentina'], 1, 'easy'),
  ('Which desert covers much of northern China and southern Mongolia?', array['Sahara','Kalahari','Gobi','Thar'], 2, 'medium'),
  ('Which country has the longest coastline in the world?', array['Australia','Russia','Canada','Indonesia'], 2, 'hard'),
  ('Which US city is famously built across a bay and known for its Golden Gate Bridge?', array['Los Angeles','San Diego','San Francisco','Seattle'], 2, 'easy'),
  ('Which country lies at both the northernmost and easternmost points of the European mainland?', array['Finland','Norway','Russia','Iceland'], 1, 'hard'),
  ('What continent is the Amazon Rainforest primarily located on?', array['Africa','Asia','South America','North America'], 2, 'easy'),
  ('Which country is the Great Barrier Reef located off the coast of?', array['Indonesia','Philippines','Australia','New Zealand'], 2, 'easy'),
  ('Which is the highest waterfall in the world?', array['Niagara Falls','Angel Falls','Victoria Falls','Iguazu Falls'], 1, 'hard'),
  ('Which African country is home to Victoria Falls, shared with Zambia?', array['Zimbabwe','Botswana','Namibia','Malawi'], 0, 'medium'),
  ('Which country has the city of Timbuktu?', array['Niger','Chad','Mali','Senegal'], 2, 'hard'),
  ('The Panama Canal connects which two oceans?', array['Atlantic and Indian','Pacific and Indian','Atlantic and Pacific','Arctic and Pacific'], 2, 'medium'),
  ('Which country is the source of the Blue Nile?', array['Sudan','Egypt','Ethiopia','Kenya'], 2, 'hard'),
  ('Which US state is separated from the mainland United States?', array['Hawaii','Florida','Maine','Rhode Island'], 0, 'easy'),
  ('Which country shares the longest land border with China?', array['Russia','Mongolia','India','Kazakhstan'], 0, 'hard'),
  ('Which country is the setting for the ancient ruins of Machu Picchu?', array['Bolivia','Peru','Chile','Ecuador'], 1, 'easy'),
  ('Which body of water is the lowest point on Earth''s land surface?', array['Caspian Sea','Dead Sea','Sea of Galilee','Aral Sea'], 1, 'medium'),
  ('Which country is Mount Fuji located in?', array['China','Japan','South Korea','Taiwan'], 1, 'easy'),
  ('Which continent has the most countries?', array['Asia','Africa','Europe','South America'], 1, 'medium'),
  ('Which country is the world''s largest exporter of coffee?', array['Colombia','Vietnam','Brazil','Ethiopia'], 2, 'medium')
) as q(prompt, options, correct_index, difficulty)
where not exists (
  select 1 from public.questions existing where existing.prompt = q.prompt
);
