-- Note: the "Call Me Maybe" question below is written directly in its final,
-- corrected form. The version originally applied to the database had leftover
-- reasoning text baked into the prompt ("...actually British? (trick: name
-- the Canadian instead)...") and was fixed in place with an UPDATE right
-- after this migration ran. This file reflects that fix so a fresh apply
-- reproduces the current, correct database state.

insert into public.questions (prompt, options, correct_index, category, difficulty)
select prompt, options, correct_index, 'Music', difficulty
from (values
  ('Which pop star released the album "1989"?', array['Katy Perry','Taylor Swift','Ariana Grande','Selena Gomez'], 1, 'easy'),
  ('Which band recorded "Stairway to Heaven"?', array['Deep Purple','Led Zeppelin','Black Sabbath','The Rolling Stones'], 1, 'medium'),
  ('Which member of the Beatles played bass guitar?', array['John Lennon','George Harrison','Paul McCartney','Ringo Starr'], 2, 'medium'),
  ('What genre of music originated in New Orleans in the early 20th century?', array['Blues','Jazz','Country','Gospel'], 1, 'medium'),
  ('Which Swedish pop group released "Dancing Queen"?', array['Roxette','Ace of Base','ABBA','A-ha'], 2, 'easy'),
  ('Which artist is known for the song "Rolling in the Deep"?', array['Adele','Sam Smith','Duffy','Florence Welch'], 0, 'easy'),
  ('Which rock band is fronted by Freddie Mercury on classic recordings?', array['Queen','The Who','Genesis','Yes'], 0, 'easy'),
  ('Which instrument does a "cellist" play?', array['Violin','Viola','Cello','Double bass'], 2, 'easy'),
  ('How many lines are on a standard musical staff?', array['4','5','6','7'], 1, 'medium'),
  ('Which composer wrote "Fur Elise"?', array['Mozart','Beethoven','Chopin','Brahms'], 1, 'easy'),
  ('Which artist released the album "Random Access Memories"?', array['Justice','Daft Punk','Chemical Brothers','Deadmau5'], 1, 'medium'),
  ('Which country music legend is known as "The Man in Black"?', array['Willie Nelson','Johnny Cash','Kris Kristofferson','Waylon Jennings'], 1, 'medium'),
  ('Which singer is known as the "Queen of Soul"?', array['Diana Ross','Aretha Franklin','Whitney Houston','Tina Turner'], 1, 'medium'),
  ('Which band released the album "Dark Side of the Moon"?', array['Led Zeppelin','Pink Floyd','The Who','Genesis'], 1, 'medium'),
  ('Which musical instrument has 88 keys?', array['Organ','Piano','Harpsichord','Accordion'], 1, 'easy'),
  ('Which girl group sang "Wannabe"?', array['Destiny''s Child','TLC','Spice Girls','En Vogue'], 2, 'easy'),
  ('Which rapper released the album "The Marshall Mathers LP"?', array['Jay-Z','50 Cent','Eminem','Kanye West'], 2, 'medium'),
  ('Which musician is known for the "Moonwalk" dance move?', array['James Brown','Michael Jackson','Prince','Usher'], 1, 'easy'),
  ('What does "a cappella" mean in music?', array['With full orchestra','Without instrumental accompaniment','Played very fast','In a minor key'], 1, 'medium'),
  ('Which composer became completely deaf later in life yet kept composing?', array['Mozart','Beethoven','Bach','Haydn'], 1, 'easy'),
  ('Which British band released "Wonderwall" and "Don''t Look Back in Anger"?', array['Blur','Pulp','Oasis','Suede'], 2, 'easy'),
  ('Which musical genre is Bob Marley most associated with?', array['Ska','Reggae','Dancehall','Calypso'], 1, 'easy'),
  ('Which US singer is known for the song "Single Ladies (Put a Ring on It)"?', array['Rihanna','Beyonce','Kelly Rowland','Ciara'], 1, 'easy'),
  ('Which orchestral section do violins, violas and cellos belong to?', array['Brass','Woodwind','Strings','Percussion'], 2, 'easy'),
  ('Which instrument is Yo-Yo Ma world famous for playing?', array['Violin','Cello','Piano','Flute'], 1, 'medium'),
  ('Which band released the concept album "The Wall"?', array['Pink Floyd','Genesis','Yes','King Crimson'], 0, 'medium'),
  ('Which singer is known as "The Piano Man"?', array['Elton John','Billy Joel','Ray Charles','Stevie Wonder'], 1, 'medium'),
  ('Which classical composer wrote "The Nutcracker"?', array['Stravinsky','Tchaikovsky','Rachmaninoff','Prokofiev'], 1, 'medium'),
  ('Which artist recorded the best-selling single "Candle in the Wind 1997"?', array['Rod Stewart','Elton John','Phil Collins','Sting'], 1, 'medium'),
  ('Which South Korean band is known for the global hit "Dynamite"?', array['EXO','BTS','Blackpink','Seventeen'], 1, 'easy'),
  ('Which musician recorded the album "Thriller"?', array['Prince','Michael Jackson','Lionel Richie','George Michael'], 1, 'easy'),
  ('Which British singer released the album "21"?', array['Adele','Duffy','Amy Winehouse','Joss Stone'], 0, 'medium'),
  ('Which instrument is central to a mariachi band alongside guitars?', array['Trumpet','Saxophone','Clarinet','Oboe'], 0, 'medium'),
  ('Which musical has the songs "Defying Gravity" and "Popular"?', array['Hamilton','Wicked','Chicago','Rent'], 1, 'medium'),
  ('Which artist is known for wearing elaborate outsized sunglasses and costumes, and the hit "Poker Face"?', array['Katy Perry','Lady Gaga','Rihanna','Nicki Minaj'], 1, 'easy'),
  ('Which musical term means "gradually getting louder"?', array['Diminuendo','Crescendo','Staccato','Legato'], 1, 'medium'),
  ('Which musical term means "gradually getting softer"?', array['Diminuendo','Crescendo','Forte','Vivace'], 0, 'hard'),
  ('Which legendary guitarist played "Purple Haze" and "Voodoo Child"?', array['Eric Clapton','Jimi Hendrix','Jimmy Page','Carlos Santana'], 1, 'medium'),
  ('Which band is fronted by Chris Martin?', array['Radiohead','Coldplay','Muse','Keane'], 1, 'easy'),
  ('Which musical features the songs "Memory" and is based on T.S. Eliot poems?', array['Cats','Les Miserables','The Phantom of the Opera','Evita'], 0, 'medium'),
  ('Which US rapper and producer released "Stronger" and "Gold Digger"?', array['Jay-Z','Kanye West','Pharrell Williams','Timbaland'], 1, 'medium'),
  ('Which instrument family does the trumpet belong to?', array['Woodwind','Brass','Percussion','Strings'], 1, 'easy'),
  ('Which singer released the breakout album "Back to Black"?', array['Duffy','Adele','Amy Winehouse','Joss Stone'], 2, 'medium'),
  ('Which iconic music festival is held annually near Pilton, England?', array['Coachella','Glastonbury','Reading Festival','Isle of Wight Festival'], 1, 'medium'),
  ('Which band performed the theme song for the James Bond film "Skyfall"?', array['Adele','Sam Smith','Shirley Bassey','Duran Duran'], 0, 'medium'),
  ('Which country is credited as the birthplace of the tango?', array['Brazil','Argentina','Spain','Cuba'], 1, 'medium'),
  ('Which pop star released the album "Lemonade" featuring the single "Formation"?', array['Rihanna','Beyonce','Alicia Keys','Solange'], 1, 'medium'),
  ('Which composer is known for "The Four Seasons"?', array['Bach','Handel','Vivaldi','Corelli'], 2, 'medium'),
  ('Which musical instrument has pedals, strings and is played with hammers?', array['Harpsichord','Piano','Organ','Harp'], 1, 'easy'),
  ('Which duo made up the electronic act Daft Punk?', array['Thomas Bangalter and Guy-Manuel de Homem-Christo','David Guetta and Afrojack','Justice and Simian','Chemical Brothers'], 0, 'hard'),
  ('Which rock band released "Bohemian Rhapsody" as part of the album "A Night at the Opera"?', array['Queen','The Who','Genesis','Yes'], 0, 'easy'),
  ('Which singer had a hit with "I Will Always Love You" for "The Bodyguard"?', array['Mariah Carey','Whitney Houston','Celine Dion','Toni Braxton'], 1, 'easy'),
  ('Which artist is known for the song "Uptown Funk" with Mark Ronson?', array['Pharrell Williams','Bruno Mars','Justin Timberlake','Usher'], 1, 'easy'),
  ('Which composer wrote the opera "The Magic Flute"?', array['Beethoven','Mozart','Wagner','Verdi'], 1, 'medium'),
  ('Which British rock band recorded "Sweet Child o'' Mine"?', array['Aerosmith','Guns N'' Roses','Bon Jovi','Def Leppard'], 1, 'easy'),
  ('Which artist is known for the song "Rehab"?', array['Duffy','Adele','Amy Winehouse','Lily Allen'], 2, 'medium'),
  ('Which record label did Motown''s founder Berry Gordy establish in Detroit?', array['Atlantic Records','Motown Records','Stax Records','Chess Records'], 1, 'medium'),
  ('Which music streaming service was founded in Sweden in 2006?', array['Deezer','Tidal','Spotify','SoundCloud'], 2, 'easy'),
  ('Which classical composer was born in Salzburg, Austria?', array['Beethoven','Mozart','Haydn','Schubert'], 1, 'easy'),
  ('Which Motown group was fronted by Diana Ross?', array['The Marvelettes','The Supremes','The Ronettes','Martha and the Vandellas'], 1, 'medium'),
  ('Which singer released the diss track "Not Like Us"?', array['Drake','Kendrick Lamar','J. Cole','Future'], 1, 'medium'),
  ('Which Canadian artist sang "Call Me Maybe"?', array['Avril Lavigne','Carly Rae Jepsen','Shania Twain','Alanis Morissette'], 1, 'medium'),
  ('Which artist''s real voice range is famously classified as a "whistle register", known for "Emotions"?', array['Whitney Houston','Mariah Carey','Christina Aguilera','Celine Dion'], 1, 'hard'),
  ('Which iconic instrument is central to flamenco music?', array['Piano','Classical guitar','Violin','Accordion'], 1, 'medium'),
  ('Which artist recorded "Shallow" for the film "A Star Is Born"?', array['Lady Gaga and Bradley Cooper','Beyonce and Jay-Z','Adele','Ariana Grande'], 0, 'medium'),
  ('Which band is known for the rock opera "Tommy"?', array['The Who','Pink Floyd','Genesis','Rush'], 0, 'hard'),
  ('Which singer is known as "The Velvet Fog"?', array['Frank Sinatra','Mel Torme','Nat King Cole','Tony Bennett'], 1, 'hard'),
  ('Which artist released the influential hip-hop album "Illmatic"?', array['Nas','Notorious B.I.G.','Jay-Z','Tupac Shakur'], 0, 'hard'),
  ('Which pop trio consists of sisters Este, Danielle and Alana?', array['HAIM','Wilson Phillips','The Chicks','First Aid Kit'], 0, 'hard'),
  ('Which musical instrument is central to a traditional Scottish band alongside drums?', array['Bagpipes','Accordion','Fiddle','Harp'], 0, 'easy'),
  ('Which singer is known for the alter ego "Sasha Fierce"?', array['Rihanna','Beyonce','Nicki Minaj','Ciara'], 1, 'hard'),
  ('Which classical period composer is known for the "Moonlight Sonata"?', array['Mozart','Beethoven','Chopin','Liszt'], 1, 'medium'),
  ('Which artist is known for the song "Bad Romance"?', array['Katy Perry','Lady Gaga','Kesha','Rihanna'], 1, 'easy'),
  ('Which band recorded "Smells Like Teen Spirit"?', array['Pearl Jam','Nirvana','Soundgarden','Alice in Chains'], 1, 'easy'),
  ('Which musical style is characterised by call-and-response singing and originated among enslaved African Americans?', array['Jazz','Blues','Gospel','Ragtime'], 2, 'hard'),
  ('Which producer and DJ is known for the stage name Deadmau5?', array['Joel Zimmerman','Tiesto','David Guetta','Calvin Harris'], 0, 'hard'),
  ('Which classic rock band released "Hotel California"?', array['Fleetwood Mac','Eagles','The Doobie Brothers','Steely Dan'], 1, 'medium'),
  ('Which artist is known for the hit "Rolling in the Deep" and the album "25"?', array['Adele','Sam Smith','Emeli Sande','Duffy'], 0, 'easy'),
  ('Which vocal range is the lowest for a typical adult male singer?', array['Tenor','Baritone','Bass','Alto'], 2, 'medium'),
  ('Which vocal range is the highest for a typical adult female singer?', array['Alto','Mezzo-soprano','Soprano','Contralto'], 2, 'medium'),
  ('Which German composer wrote the "Ode to Joy" as part of his Ninth Symphony?', array['Bach','Beethoven','Brahms','Wagner'], 1, 'medium')
) as q(prompt, options, correct_index, difficulty)
where not exists (
  select 1 from public.questions existing where existing.prompt = q.prompt
);
