insert into public.questions (prompt, options, correct_index, category, difficulty)
select prompt, options, correct_index, 'History', difficulty
from (values
  ('Who was the Emperor of France crowned in 1804?', array['Louis XVI','Napoleon Bonaparte','Charles de Gaulle','Louis Philippe'], 1, 'medium'),
  ('In which year did the French Revolution begin?', array['1776','1789','1799','1804'], 1, 'medium'),
  ('Which ancient civilisation built the pyramids at Giza?', array['Mesopotamian','Egyptian','Mayan','Roman'], 1, 'easy'),
  ('Who was the first Roman Emperor?', array['Julius Caesar','Augustus','Nero','Constantine'], 1, 'medium'),
  ('In which year did Christopher Columbus first reach the Americas?', array['1492','1500','1607','1620'], 0, 'easy'),
  ('Which country was the first to grant women the right to vote nationally?', array['United States','United Kingdom','New Zealand','France'], 2, 'hard'),
  ('Who was the leader of Nazi Germany during World War II?', array['Joseph Stalin','Benito Mussolini','Adolf Hitler','Heinrich Himmler'], 2, 'easy'),
  ('Which country did Hitler invade in 1939, triggering the start of World War II?', array['France','Poland','Belgium','Austria'], 1, 'medium'),
  ('On what date did the D-Day landings take place?', array['1 May 1944','6 June 1944','15 August 1944','25 December 1944'], 1, 'medium'),
  ('Which US city was hit by an atomic bomb on 6 August 1945?', array['Nagasaki','Tokyo','Hiroshima','Kyoto'], 2, 'medium'),
  ('Who was the President of the United States during the American Civil War?', array['Andrew Jackson','Abraham Lincoln','Ulysses S. Grant','James Buchanan'], 1, 'easy'),
  ('In which year did the American Civil War end?', array['1860','1863','1865','1870'], 2, 'medium'),
  ('Which document did King John of England sign in 1215?', array['The Domesday Book','The Magna Carta','The Bill of Rights','The Treaty of Windsor'], 1, 'medium'),
  ('Who led the Soviet Union during the Cuban Missile Crisis?', array['Joseph Stalin','Nikita Khrushchev','Leonid Brezhnev','Vladimir Lenin'], 1, 'medium'),
  ('Which explorer led the first expedition to circumnavigate the globe?', array['Christopher Columbus','Vasco da Gama','Ferdinand Magellan','James Cook'], 2, 'medium'),
  ('Which queen ruled England during the defeat of the Spanish Armada in 1588?', array['Mary I','Elizabeth I','Victoria','Anne'], 1, 'medium'),
  ('Which wall divided East and West Berlin from 1961 to 1989?', array['Hadrian''s Wall','The Berlin Wall','The Great Wall','The Atlantic Wall'], 1, 'easy'),
  ('Who was assassinated in Sarajevo in 1914, triggering the start of World War I?', array['Kaiser Wilhelm II','Archduke Franz Ferdinand','Tsar Nicholas II','King George V'], 1, 'medium'),
  ('Which ancient wonder of the world was located in Alexandria, Egypt?', array['The Colossus of Rhodes','The Lighthouse of Alexandria','The Hanging Gardens','The Temple of Artemis'], 1, 'hard'),
  ('Who was the first Emperor of a unified China?', array['Confucius','Qin Shi Huang','Sun Tzu','Kublai Khan'], 1, 'hard'),
  ('Which explorer is credited with reaching the South Pole first, in 1911?', array['Robert Falcon Scott','Roald Amundsen','Ernest Shackleton','Douglas Mawson'], 1, 'hard'),
  ('Which ship famously sank on its maiden voyage in 1912?', array['Lusitania','Britannic','Titanic','Olympic'], 2, 'easy'),
  ('Who was the leader of India''s non-violent independence movement?', array['Jawaharlal Nehru','Mahatma Gandhi','Subhas Chandra Bose','Muhammad Ali Jinnah'], 1, 'easy'),
  ('In which year did India gain independence from Britain?', array['1945','1947','1950','1952'], 1, 'medium'),
  ('Which empire was ruled by Genghis Khan?', array['Ottoman Empire','Mongol Empire','Persian Empire','Roman Empire'], 1, 'medium'),
  ('Which philosopher was sentenced to death by drinking hemlock in ancient Athens?', array['Aristotle','Plato','Socrates','Pythagoras'], 2, 'medium'),
  ('Which dynasty built the Taj Mahal?', array['Maratha','Mughal','Gupta','Maurya'], 1, 'medium'),
  ('Which country was the first to industrialise, starting in the 18th century?', array['France','Germany','United Kingdom','United States'], 2, 'medium'),
  ('Who was the last Tsar of Russia?', array['Alexander III','Nicholas II','Peter the Great','Ivan the Terrible'], 1, 'medium'),
  ('In which century did the Black Death devastate Europe?', array['12th century','14th century','16th century','18th century'], 1, 'medium'),
  ('Which country did Julius Caesar famously invade in 55 BC?', array['Gaul','Britain','Egypt','Greece'], 1, 'hard'),
  ('Who painted the Sistine Chapel ceiling?', array['Leonardo da Vinci','Raphael','Michelangelo','Donatello'], 2, 'easy'),
  ('Which revolution in Russia in 1917 led to the fall of the Tsar?', array['The Bolshevik Revolution','The Cultural Revolution','The Velvet Revolution','The October Uprising'], 0, 'medium'),
  ('Which US president signed the Emancipation Proclamation?', array['Andrew Johnson','Abraham Lincoln','Ulysses S. Grant','James Garfield'], 1, 'medium'),
  ('Which ancient city-state is credited with founding democracy?', array['Sparta','Athens','Corinth','Thebes'], 1, 'easy'),
  ('Which country built the Great Wall to defend against northern invasions?', array['Japan','Mongolia','China','Korea'], 2, 'easy'),
  ('Who was crowned Holy Roman Emperor in 800 AD?', array['Charlemagne','Otto I','Frederick Barbarossa','Charles V'], 0, 'hard'),
  ('Which vaccine did Edward Jenner pioneer in 1796?', array['Rabies','Smallpox','Polio','Tetanus'], 1, 'medium'),
  ('Which country dropped the first practical steam locomotive railway into service in the 1820s?', array['France','Germany','United Kingdom','United States'], 2, 'hard'),
  ('Which US president served during the Great Depression and introduced the New Deal?', array['Herbert Hoover','Franklin D. Roosevelt','Calvin Coolidge','Harry Truman'], 1, 'medium'),
  ('Which country was divided into North and South after World War II, leading to a war in the 1950s?', array['Vietnam','Korea','Germany','China'], 1, 'medium'),
  ('Which civil rights leader delivered the "I Have a Dream" speech in 1963?', array['Malcolm X','Martin Luther King Jr.','Rosa Parks','John Lewis'], 1, 'easy'),
  ('Who was the first man to walk on the Moon, in 1969?', array['Buzz Aldrin','Michael Collins','Neil Armstrong','Yuri Gagarin'], 2, 'easy'),
  ('Which country launched the first artificial satellite, Sputnik, in 1957?', array['United States','Soviet Union','United Kingdom','China'], 1, 'medium'),
  ('Which prehistoric monument stands on Salisbury Plain in England?', array['Avebury','Stonehenge','Newgrange','Callanish'], 1, 'easy'),
  ('Which explorer''s voyages were funded by the Spanish crown starting in 1492?', array['Vasco da Gama','Christopher Columbus','Hernan Cortes','Ferdinand Magellan'], 1, 'easy'),
  ('Which treaty officially ended World War I in 1919?', array['Treaty of Paris','Treaty of Versailles','Treaty of Vienna','Treaty of Ghent'], 1, 'medium'),
  ('Which ancient empire was ruled from the city of Constantinople?', array['Ottoman Empire','Byzantine Empire','Persian Empire','Roman Republic'], 1, 'hard'),
  ('Which British king had six wives?', array['George III','Henry VII','Henry VIII','Richard III'], 2, 'easy'),
  ('Which queen was famously executed on the orders of Henry VIII?', array['Catherine of Aragon','Anne Boleyn','Jane Seymour','Catherine Parr'], 1, 'medium'),
  ('Which country''s Cultural Revolution, led by Mao Zedong, began in 1966?', array['Vietnam','North Korea','China','Cambodia'], 2, 'medium'),
  ('Which African leader became the country''s first Black president in 1994?', array['Robert Mugabe','Nelson Mandela','Kenneth Kaunda','Julius Nyerere'], 1, 'easy'),
  ('Which war lasted from 1955 to 1975 and involved the United States heavily?', array['Korean War','Vietnam War','Gulf War','Iran-Iraq War'], 1, 'easy'),
  ('Which country did Britain go to war with over the Falkland Islands in 1982?', array['Chile','Argentina','Brazil','Uruguay'], 1, 'medium'),
  ('Which US scandal led to President Nixon''s resignation in 1974?', array['Iran-Contra','Watergate','Whitewater','Teapot Dome'], 1, 'medium'),
  ('Which country was formerly known as Persia?', array['Iraq','Iran','Turkey','Syria'], 1, 'medium'),
  ('Which explorer became the first European to sail around the Cape of Good Hope?', array['Vasco da Gama','Bartolomeu Dias','Prince Henry the Navigator','Ferdinand Magellan'], 1, 'hard'),
  ('Which country was unified under Otto von Bismarck in 1871?', array['Italy','Germany','Austria','Poland'], 1, 'medium'),
  ('Which Italian city-state produced the Renaissance masters Michelangelo and Leonardo da Vinci?', array['Venice','Rome','Florence','Milan'], 2, 'medium'),
  ('Which US amendment abolished slavery?', array['13th Amendment','14th Amendment','15th Amendment','19th Amendment'], 0, 'medium'),
  ('Which country was the first to send a human into space?', array['United States','Soviet Union','China','United Kingdom'], 1, 'easy'),
  ('Who was the first person in space, in 1961?', array['Neil Armstrong','Yuri Gagarin','Alan Shepard','John Glenn'], 1, 'medium'),
  ('Which ancient Greek city-state was renowned for its military discipline?', array['Athens','Sparta','Corinth','Thebes'], 1, 'easy'),
  ('Which pharaoh''s tomb, discovered nearly intact in 1922, made Howard Carter famous?', array['Ramesses II','Akhenaten','Tutankhamun','Cleopatra'], 2, 'medium'),
  ('Which country was ruled by the Romanov dynasty until 1917?', array['Poland','Russia','Austria','Prussia'], 1, 'medium'),
  ('Which war was fought between Athens and Sparta in ancient Greece?', array['The Trojan War','The Peloponnesian War','The Persian War','The Punic War'], 1, 'hard'),
  ('Which explorer is credited with the first recorded European sighting of Australia?', array['James Cook','Abel Tasman','Willem Janszoon','Matthew Flinders'], 2, 'hard'),
  ('Which country annexed Hawaii in 1898?', array['United Kingdom','United States','France','Japan'], 1, 'medium'),
  ('Which US President purchased Louisiana from France in 1803?', array['George Washington','John Adams','Thomas Jefferson','James Madison'], 2, 'medium'),
  ('Which revolution overthrew the French monarchy for the final time in 1848?', array['The July Revolution','The February Revolution','The Bourbon Restoration','The Thermidorian Reaction'], 1, 'hard'),
  ('Which country was the Ottoman Empire centred in?', array['Egypt','Turkey','Saudi Arabia','Iran'], 1, 'medium'),
  ('Which US city was the site of the Boston Tea Party in 1773?', array['New York','Philadelphia','Boston','Baltimore'], 2, 'easy'),
  ('Which country''s revolution in 1959 brought Fidel Castro to power?', array['Nicaragua','Cuba','Venezuela','Chile'], 1, 'medium'),
  ('Which ancient structure in Rome was used for gladiatorial combat?', array['The Pantheon','The Colosseum','The Forum','The Circus Maximus'], 1, 'easy'),
  ('Which country was the first to abolish the transatlantic slave trade, in 1807?', array['United States','France','Britain','Portugal'], 2, 'hard'),
  ('Which US president was in office during the attack on Pearl Harbor?', array['Herbert Hoover','Franklin D. Roosevelt','Harry Truman','Dwight Eisenhower'], 1, 'medium'),
  ('Which country was split by the Iron Curtain during the Cold War, along with the rest of Europe?', array['Spain','Germany','Italy','Switzerland'], 1, 'easy'),
  ('Which British Prime Minister famously said "Blood, toil, tears and sweat"?', array['Neville Chamberlain','Winston Churchill','Clement Attlee','Anthony Eden'], 1, 'medium'),
  ('Which country was the first to walk on the moon''s surface, via NASA''s Apollo program?', array['Soviet Union','United States','United Kingdom','China'], 1, 'easy')
) as q(prompt, options, correct_index, difficulty)
where not exists (
  select 1 from public.questions existing where existing.prompt = q.prompt
);

-- Applied as part of 0017 originally (a small top-up alongside Random Facts);
-- listed here since it is a History row.
insert into public.questions (prompt, options, correct_index, category, difficulty)
select 'Which US President served the shortest term in office, dying just 31 days in?',
       array['William Henry Harrison','Zachary Taylor','James A. Garfield','Warren G. Harding'], 0, 'History', 'hard'
where not exists (
  select 1 from public.questions where prompt = 'Which US President served the shortest term in office, dying just 31 days in?'
);
