insert into public.questions (prompt, options, correct_index, category, difficulty)
select prompt, options, correct_index, 'Science & Nature', difficulty
from (values
  ('What is the chemical symbol for sodium?', array['So','Sd','Na','Su'], 2, 'medium'),
  ('What is the chemical symbol for potassium?', array['Po','Pt','Ps','K'], 3, 'medium'),
  ('What is the largest organ in the human body?', array['Liver','Brain','Skin','Lungs'], 2, 'medium'),
  ('Which planet has the most moons in our solar system?', array['Jupiter','Saturn','Uranus','Neptune'], 1, 'hard'),
  ('What force keeps planets in orbit around the Sun?', array['Magnetism','Gravity','Friction','Inertia'], 1, 'easy'),
  ('What is the process by which plants make their own food called?', array['Respiration','Photosynthesis','Fermentation','Transpiration'], 1, 'easy'),
  ('What is the smallest unit of life?', array['Atom','Molecule','Cell','Tissue'], 2, 'easy'),
  ('Which gas do humans exhale in the largest amount?', array['Oxygen','Carbon dioxide','Nitrogen','Hydrogen'], 1, 'medium'),
  ('What is the study of living organisms called?', array['Geology','Biology','Chemistry','Physics'], 1, 'easy'),
  ('What is the freezing point of water in Celsius?', array['-10','0','10','32'], 1, 'easy'),
  ('What is the freezing point of water in Fahrenheit?', array['0','32','100','212'], 1, 'medium'),
  ('Which element has the chemical symbol O?', array['Osmium','Oxygen','Gold','Silver'], 1, 'easy'),
  ('Which element has the chemical symbol H?', array['Helium','Hydrogen','Mercury','Hafnium'], 1, 'easy'),
  ('What is the powerhouse of the cell, producing energy?', array['Nucleus','Ribosome','Mitochondria','Chloroplast'], 2, 'easy'),
  ('Which type of animal is a frog?', array['Reptile','Amphibian','Mammal','Fish'], 1, 'easy'),
  ('Which is the fastest bird in the world in level flight?', array['Golden eagle','Peregrine falcon','Common swift','Gyrfalcon'], 2, 'hard'),
  ('Which animal has the longest gestation period among mammals?', array['Blue whale','Elephant','Giraffe','Rhinoceros'], 1, 'medium'),
  ('What do you call an animal that eats only plants?', array['Carnivore','Herbivore','Omnivore','Insectivore'], 1, 'easy'),
  ('What do you call an animal that eats both plants and meat?', array['Carnivore','Herbivore','Omnivore','Detritivore'], 2, 'easy'),
  ('Which layer of the Earth is the hottest?', array['Crust','Mantle','Outer core','Inner core'], 3, 'medium'),
  ('What is the outermost layer of the Earth called?', array['Mantle','Crust','Core','Lithosphere'], 1, 'easy'),
  ('What is the study of the weather and atmosphere called?', array['Geology','Meteorology','Astronomy','Oceanography'], 1, 'medium'),
  ('Which planet is famous for its prominent ring system?', array['Jupiter','Saturn','Uranus','Neptune'], 1, 'easy'),
  ('Which is the closest star to Earth?', array['Proxima Centauri','The Sun','Alpha Centauri','Sirius'], 1, 'easy'),
  ('What is the term for an animal that is active at night?', array['Diurnal','Nocturnal','Crepuscular','Dormant'], 1, 'easy'),
  ('What is the largest land animal on Earth?', array['White rhinoceros','African elephant','Giraffe','Hippopotamus'], 1, 'easy'),
  ('Which sense organ is responsible for detecting light?', array['Ear','Nose','Eye','Tongue'], 2, 'easy'),
  ('What is the human skeleton''s primary mineral component?', array['Iron','Calcium','Potassium','Zinc'], 1, 'medium'),
  ('Which gas makes up about 78% of Earth''s atmosphere?', array['Oxygen','Carbon dioxide','Nitrogen','Argon'], 2, 'medium'),
  ('What is the term for a baby kangaroo?', array['Cub','Joey','Kid','Calf'], 1, 'easy'),
  ('What is the term for a baby cow?', array['Foal','Calf','Kid','Lamb'], 1, 'easy'),
  ('What is the term for a group of lions called?', array['A herd','A pack','A pride','A flock'], 2, 'easy'),
  ('What is the term for a group of wolves called?', array['A pack','A pride','A herd','A colony'], 0, 'easy'),
  ('Which blood cells are responsible for fighting infection?', array['Red blood cells','White blood cells','Platelets','Plasma cells'], 1, 'medium'),
  ('What is the main function of red blood cells?', array['Fight infection','Carry oxygen','Clot blood','Produce hormones'], 1, 'medium'),
  ('Which vitamin is also known as ascorbic acid?', array['Vitamin A','Vitamin B12','Vitamin C','Vitamin D'], 2, 'medium'),
  ('Which part of the plant conducts photosynthesis?', array['Roots','Stem','Leaves','Flowers'], 2, 'easy'),
  ('What is the pH value of pure water considered neutral?', array['0','7','10','14'], 1, 'medium'),
  ('What is the boiling point of water in Fahrenheit?', array['180','200','212','220'], 2, 'medium'),
  ('Which scientist developed the theory of general relativity?', array['Isaac Newton','Albert Einstein','Niels Bohr','Galileo Galilei'], 1, 'easy'),
  ('Which scientist formulated the laws of motion and universal gravitation?', array['Albert Einstein','Isaac Newton','Galileo Galilei','Johannes Kepler'], 1, 'easy'),
  ('Which naturalist proposed the theory of evolution by natural selection?', array['Gregor Mendel','Charles Darwin','Alfred Russel Wallace','Louis Pasteur'], 1, 'easy'),
  ('Which scientist is credited with discovering penicillin?', array['Louis Pasteur','Alexander Fleming','Robert Koch','Edward Jenner'], 1, 'medium'),
  ('What type of animal is a dolphin?', array['Fish','Amphibian','Mammal','Reptile'], 2, 'easy'),
  ('Which organ pumps blood around the human body?', array['Lungs','Liver','Heart','Kidneys'], 2, 'easy'),
  ('Which organs are responsible for filtering waste from the blood?', array['Lungs','Kidneys','Liver','Stomach'], 1, 'medium'),
  ('What is the largest planet in our solar system by volume?', array['Saturn','Jupiter','Uranus','Neptune'], 1, 'easy'),
  ('Which is the smallest planet in our solar system?', array['Mars','Mercury','Venus','Pluto'], 1, 'medium'),
  ('What is the process by which water turns into vapour called?', array['Condensation','Evaporation','Precipitation','Sublimation'], 1, 'easy'),
  ('What is the process by which water vapour turns back into liquid called?', array['Evaporation','Condensation','Precipitation','Sublimation'], 1, 'medium'),
  ('Which force pulls objects towards the centre of the Earth?', array['Magnetism','Gravity','Friction','Tension'], 1, 'easy'),
  ('Which type of rock is formed from cooled volcanic lava?', array['Sedimentary','Metamorphic','Igneous','Fossil'], 2, 'medium'),
  ('What is the study of rocks and the Earth''s physical structure called?', array['Biology','Geology','Astronomy','Ecology'], 1, 'medium'),
  ('Which animal is known for changing colour to camouflage itself?', array['Chameleon','Iguana','Gecko','Salamander'], 0, 'easy'),
  ('Which sea creature has eight arms?', array['Squid','Octopus','Jellyfish','Starfish'], 1, 'easy'),
  ('Which is the tallest animal in the world?', array['Elephant','Giraffe','Ostrich','Camel'], 1, 'easy'),
  ('Which mammal is known to lay eggs?', array['Kangaroo','Platypus','Koala','Wombat'], 1, 'medium'),
  ('What is a group of fish called?', array['A pack','A school','A herd','A pride'], 1, 'easy'),
  ('What is a group of crows called?', array['A murder','A flock','A gaggle','A parliament'], 0, 'medium'),
  ('Which insect is known for its pollination role and produces honey?', array['Wasp','Bee','Ant','Beetle'], 1, 'easy'),
  ('Which gas is essential for combustion, or burning?', array['Nitrogen','Oxygen','Carbon dioxide','Hydrogen'], 1, 'easy'),
  ('What natural phenomenon is caused by the refraction of light through water droplets?', array['Aurora','Rainbow','Halo','Mirage'], 1, 'easy'),
  ('Which natural event is measured using the Richter scale?', array['Hurricanes','Earthquakes','Tornadoes','Volcanic eruptions'], 1, 'easy'),
  ('What is the largest species of shark, also a filter feeder?', array['Great white shark','Whale shark','Tiger shark','Hammerhead shark'], 1, 'medium'),
  ('Which part of the human body contains the smallest bones?', array['Hand','Foot','Ear','Skull'], 2, 'hard'),
  ('What is the term for an animal without a backbone?', array['Vertebrate','Invertebrate','Mammal','Amphibian'], 1, 'easy'),
  ('Which planet is known for having the Great Red Spot, a giant storm?', array['Mars','Jupiter','Saturn','Neptune'], 1, 'easy'),
  ('What is the primary gas found in the Sun that fuels its energy?', array['Oxygen','Hydrogen','Helium','Nitrogen'], 1, 'medium'),
  ('Which natural satellite orbits the Earth?', array['Mars','The Moon','The Sun','Venus'], 1, 'easy'),
  ('What causes the tides on Earth?', array['Wind patterns','The Moon''s gravitational pull','Ocean currents','Earth''s rotation'], 1, 'medium'),
  ('What is the name for the imaginary line around which the Earth spins?', array['The equator','The axis','The meridian','The horizon'], 1, 'medium'),
  ('Which continent is home to the most species of big cats?', array['Asia','Africa','South America','Australia'], 1, 'medium'),
  ('Which is the largest species of bear?', array['Grizzly bear','Polar bear','Black bear','Panda bear'], 1, 'medium'),
  ('What is the term for animals that hibernate through winter?', array['Migratory','Hibernating','Nocturnal','Dormant'], 1, 'easy'),
  ('Which part of a plant absorbs water and nutrients from the soil?', array['Leaves','Stem','Roots','Flowers'], 2, 'easy'),
  ('What is the chemical formula for water?', array['CO2','H2O','O2','NaCl'], 1, 'easy'),
  ('What is the chemical formula for table salt?', array['H2O','NaCl','KCl','CaCO3'], 1, 'medium'),
  ('Which scientist is known for the periodic table of elements?', array['Marie Curie','Dmitri Mendeleev','Antoine Lavoisier','Niels Bohr'], 1, 'medium'),
  ('Which scientist discovered radioactivity along with her husband?', array['Rosalind Franklin','Marie Curie','Ada Lovelace','Lise Meitner'], 1, 'medium'),
  ('What is the term for the variety of life in a particular habitat?', array['Ecosystem','Biodiversity','Habitat','Population'], 1, 'medium'),
  ('Which is the largest ocean animal, also the largest animal ever known?', array['Great white shark','Blue whale','Giant squid','Orca'], 1, 'easy'),
  ('What is the name of the layer of gases that protects Earth from harmful UV radiation?', array['Troposphere','Ozone layer','Ionosphere','Stratosphere'], 1, 'medium')
) as q(prompt, options, correct_index, difficulty)
where not exists (
  select 1 from public.questions existing where existing.prompt = q.prompt
);
