insert into public.questions (prompt, options, correct_index, category, difficulty)
select prompt, options, correct_index, 'Film & TV', difficulty
from (values
  ('Which film won the first ever Academy Award for Best Picture?', array['Wings','Sunrise','Metropolis','The Jazz Singer'], 0, 'hard'),
  ('Which studio produced the "Shrek" film series?', array['Pixar','DreamWorks','Illumination','Blue Sky'], 1, 'easy'),
  ('In "Toy Story", who is Woody''s owner?', array['Sid','Andy','Buzz','Al'], 1, 'easy'),
  ('Which fictional wizarding school does Harry Potter attend?', array['Beauxbatons','Durmstrang','Hogwarts','Ilvermorny'], 2, 'easy'),
  ('What is the name of the ship in "Titanic"?', array['RMS Olympic','RMS Titanic','RMS Britannic','RMS Lusitania'], 1, 'easy'),
  ('Which film features the character Tony Stark?', array['Batman Begins','Iron Man','Man of Steel','The Dark Knight'], 1, 'easy'),
  ('Which TV show features the character Michael Scott as a regional manager?', array['Parks and Recreation','The Office','Community','Brooklyn Nine-Nine'], 1, 'easy'),
  ('Which sitcom is set in a coffee shop called Central Perk?', array['Seinfeld','How I Met Your Mother','Friends','Frasier'], 2, 'easy'),
  ('Which TV series is set in the fictional town of Hawkins, Indiana?', array['Riverdale','Stranger Things','Twin Peaks','Wayward Pines'], 1, 'easy'),
  ('Which animated series features the family the Simpsons?', array['Family Guy','The Simpsons','King of the Hill','American Dad'], 1, 'easy'),
  ('Which film franchise features a British spy with the code number 007?', array['Mission Impossible','James Bond','Kingsman','The Bourne Identity'], 1, 'easy'),
  ('Which actor played the lead role in "Forrest Gump"?', array['Tom Hanks','Kevin Costner','Robin Williams','Bill Murray'], 0, 'easy'),
  ('Who directed "Jurassic Park"?', array['George Lucas','Steven Spielberg','James Cameron','Ridley Scott'], 1, 'easy'),
  ('Which film series is set in Middle-earth?', array['Chronicles of Narnia','The Lord of the Rings','Game of Thrones','Eragon'], 1, 'easy'),
  ('Who directed the "Star Wars" original trilogy''s first film?', array['Steven Spielberg','George Lucas','James Cameron','Irvin Kershner'], 1, 'easy'),
  ('Which actor played the Terminator?', array['Sylvester Stallone','Arnold Schwarzenegger','Jean-Claude Van Damme','Dolph Lundgren'], 1, 'easy'),
  ('Which TV series features dragons and the Iron Throne?', array['The Witcher','Game of Thrones','Vikings','The Last Kingdom'], 1, 'easy'),
  ('Which animated film features a snowman named Olaf?', array['Tangled','Frozen','Moana','Encanto'], 1, 'easy'),
  ('Which actress played Elizabeth Swann in "Pirates of the Caribbean"?', array['Kate Winslet','Keira Knightley','Naomi Watts','Rachel Weisz'], 1, 'medium'),
  ('Which film won the Academy Award for Best Picture in 1994?', array['Pulp Fiction','Forrest Gump','The Shawshank Redemption','Speed'], 1, 'medium'),
  ('Which director is known for "Jaws", "E.T." and "Jurassic Park"?', array['Steven Spielberg','George Lucas','Ron Howard','Robert Zemeckis'], 0, 'easy'),
  ('Which sitcom features the characters Ross, Rachel, Monica, Chandler, Joey and Phoebe?', array['Frasier','Seinfeld','Friends','Cheers'], 2, 'easy'),
  ('Which crime drama series follows a chemistry teacher turned drug manufacturer?', array['Ozark','Breaking Bad','Better Call Saul','The Wire'], 1, 'easy'),
  ('Which fantasy series is based on the novels by George R. R. Martin?', array['The Wheel of Time','Game of Thrones','The Witcher','Shadow and Bone'], 1, 'easy'),
  ('Which actor plays Captain Jack Sparrow in "Pirates of the Caribbean"?', array['Orlando Bloom','Johnny Depp','Geoffrey Rush','Javier Bardem'], 1, 'easy'),
  ('Which film features a character who says "May the Force be with you"?', array['Star Trek','Star Wars','Guardians of the Galaxy','Dune'], 1, 'easy'),
  ('Which Pixar film is about emotions inside a young girl''s mind?', array['Coco','Inside Out','Soul','Up'], 1, 'easy'),
  ('Which actor voices Woody in "Toy Story"?', array['Tim Allen','Tom Hanks','Billy Crystal','John Ratzenberger'], 1, 'easy'),
  ('Which movie features a hotel called the Overlook?', array['Psycho','The Shining','Rosemary''s Baby','The Amityville Horror'], 1, 'medium'),
  ('Which TV series features a chess prodigy named Beth Harmon?', array['The Crown','The Queen''s Gambit','Bridgerton','Mindhunter'], 1, 'medium'),
  ('Which superhero film series features Peter Parker?', array['Batman','Spider-Man','Superman','Daredevil'], 1, 'easy'),
  ('Which actor played the Joker in "The Dark Knight"?', array['Jared Leto','Heath Ledger','Jack Nicholson','Joaquin Phoenix'], 1, 'easy'),
  ('Which sitcom is set at a bar in Boston "where everybody knows your name"?', array['Cheers','Frasier','Taxi','It''s Always Sunny in Philadelphia'], 0, 'medium'),
  ('Which animated film series features a green ogre?', array['Madagascar','Shrek','Trolls','Kung Fu Panda'], 1, 'easy'),
  ('Which film is famous for the line "I''m the king of the world"?', array['Titanic','The Great Gatsby','Gladiator','Braveheart'], 0, 'easy'),
  ('Which movie franchise features cars that transform into robots?', array['Transformers','Robocop','iRobot','Pacific Rim'], 0, 'easy'),
  ('Which TV series follows a group of survivors during a zombie apocalypse?', array['World War Z','The Walking Dead','Z Nation','Fear the Walking Dead'], 1, 'easy'),
  ('Which movie features a shark terrorising a beach town called Amity Island?', array['Deep Blue Sea','Jaws','The Meg','Open Water'], 1, 'easy'),
  ('Which musical film stars Hugh Jackman as circus founder P.T. Barnum?', array['La La Land','The Greatest Showman','Moulin Rouge','Chicago'], 1, 'medium'),
  ('Which TV comedy is set in a Pennsylvania paper company called Dunder Mifflin?', array['Parks and Recreation','The Office','Superstore','Brooklyn Nine-Nine'], 1, 'easy'),
  ('Which film series follows a boy wizard and his friends at a magical school?', array['Percy Jackson','Harry Potter','Narnia','His Dark Materials'], 1, 'easy'),
  ('Which actress played Hermione Granger?', array['Emma Watson','Bonnie Wright','Evanna Lynch','Katie Leung'], 0, 'easy'),
  ('Which sci-fi film series features lightsabers and the Force?', array['Star Trek','Star Wars','Dune','Guardians of the Galaxy'], 1, 'easy'),
  ('Which TV series is a prequel to "Breaking Bad" focusing on a lawyer?', array['Ozark','Better Call Saul','The Wire','Fargo'], 1, 'easy'),
  ('Which director made "Pulp Fiction" and "Kill Bill"?', array['Martin Scorsese','Quentin Tarantino','David Fincher','Guy Ritchie'], 1, 'easy'),
  ('Which movie features Andy Dufresne escaping from Shawshank prison?', array['The Green Mile','The Shawshank Redemption','Escape from Alcatraz','Cool Hand Luke'], 1, 'medium'),
  ('Which animated film is set in the Colombian mountains and features the Madrigal family?', array['Coco','Encanto','Moana','Luca'], 1, 'easy'),
  ('Which TV series features a group of friends navigating their twenties in New York, premiering in 1994?', array['Sex and the City','Friends','Seinfeld','How I Met Your Mother'], 1, 'medium'),
  ('Which actor played Iron Man/Tony Stark?', array['Chris Evans','Robert Downey Jr.','Mark Ruffalo','Jeremy Renner'], 1, 'easy'),
  ('Which movie is about a great white shark terrorising Amity Island, directed by Spielberg?', array['Jaws','Orca','The Deep','The Reef'], 0, 'easy'),
  ('Which film series features Middle-earth hobbits on a quest to destroy a ring?', array['The Chronicles of Narnia','The Lord of the Rings','Eragon','Willow'], 1, 'easy'),
  ('Which crime drama focuses on Baltimore''s drug trade and police force?', array['The Wire','The Shield','Homicide: Life on the Street','Boardwalk Empire'], 0, 'hard'),
  ('Which TV series features Don Draper working at an advertising agency?', array['Mad Men','Suits','Billions','Succession'], 0, 'medium'),
  ('Which movie musical features "Defying Gravity", based on the Broadway show?', array['Wicked','Chicago','Rent','Hairspray'], 0, 'medium'),
  ('Which actor played Neo in "The Matrix" trilogy?', array['Keanu Reeves','Laurence Fishburne','Hugo Weaving','Carrie-Anne Moss'], 0, 'easy'),
  ('Which sitcom features Sheldon Cooper as a socially awkward physicist?', array['Silicon Valley','The Big Bang Theory','Community','Young Sheldon'], 1, 'easy'),
  ('Which TV series follows the Crawley family and their servants in the early 20th century?', array['The Crown','Downton Abbey','Bridgerton','Victoria'], 1, 'easy'),
  ('Which film features a character named Rocky Balboa?', array['Raging Bull','Rocky','The Fighter','Creed'], 1, 'easy'),
  ('Which movie is about a great white shark and features the tagline "You''ll never go in the water again"?', array['Jaws','The Meg','Deep Blue Sea','47 Meters Down'], 0, 'medium'),
  ('Which TV series is set in a fictional version of the British royal family''s history?', array['Victoria','The Crown','Wolf Hall','Poldark'], 1, 'easy'),
  ('Which actor played Batman in "The Dark Knight" trilogy?', array['George Clooney','Christian Bale','Val Kilmer','Michael Keaton'], 1, 'easy'),
  ('Which movie features the quote "Here''s looking at you, kid"?', array['Gone with the Wind','Casablanca','Rebecca','Notorious'], 1, 'medium'),
  ('Which TV series follows the residents of Westeros and Essos?', array['The Witcher','Game of Thrones','Vikings','His Dark Materials'], 1, 'easy'),
  ('Which movie is about a group of toys that come to life when humans are not around?', array['The Brave Little Toaster','Toy Story','Small Soldiers','The Indian in the Cupboard'], 1, 'easy'),
  ('Which film franchise stars Tom Cruise as agent Ethan Hunt?', array['James Bond','Mission: Impossible','The Bourne Identity','John Wick'], 1, 'easy'),
  ('Which animated series is set in the underwater city of Bikini Bottom?', array['Finding Nemo','SpongeBob SquarePants','The Little Mermaid','Shark Tale'], 1, 'easy'),
  ('Which TV series follows Walter White''s former student Jesse Pinkman as a co-lead?', array['Better Call Saul','Breaking Bad','Ozark','Narcos'], 1, 'easy'),
  ('Which movie is about a clownfish searching for his missing son?', array['Shark Tale','Finding Nemo','The Little Mermaid','Moana'], 1, 'easy'),
  ('Which film series features a British secret agent who drinks his martini "shaken, not stirred"?', array['Kingsman','James Bond','Mission: Impossible','The Man from U.N.C.L.E.'], 1, 'easy'),
  ('Which movie features a boy who befriends an alien and helps him phone home?', array['Close Encounters of the Third Kind','E.T. the Extra-Terrestrial','Cocoon','Flight of the Navigator'], 1, 'easy'),
  ('Which TV series is set in a fictional Italian-American crime family in New Jersey?', array['Goodfellas','The Sopranos','Boardwalk Empire','The Godfather'], 1, 'medium'),
  ('Which director is known for "Goodfellas" and "Taxi Driver"?', array['Francis Ford Coppola','Martin Scorsese','Brian De Palma','Michael Cimino'], 1, 'medium'),
  ('Which movie features a young lion named Simba who becomes king?', array['Madagascar','The Lion King','Tarzan','Zootopia'], 1, 'easy'),
  ('Which TV series follows Eleven and her friends battling the Upside Down?', array['Dark','Stranger Things','The OA','Locke & Key'], 1, 'easy'),
  ('Which movie is about a robot who falls in love while cleaning up a deserted Earth?', array['Wall-E','Big Hero 6','The Iron Giant','Robots'], 0, 'easy'),
  ('Which TV series is a spinoff following the Winchester brothers hunting monsters?', array['Supernatural','Charmed','Grimm','Constantine'], 0, 'medium'),
  ('Which film franchise features Vin Diesel as Dominic Toretto?', array['The Transporter','Fast & Furious','xXx','Need for Speed'], 1, 'easy'),
  ('Which movie features the fictional country of Wakanda?', array['Black Panther','Coming to America','The Lion King','Blood Diamond'], 0, 'easy'),
  ('Which sitcom features a group of paleontology-obsessed friends including Leonard and Sheldon?', array['The Big Bang Theory','Community','New Girl','Silicon Valley'], 0, 'easy'),
  ('Which movie is about a group of astronauts stranded after their mission to Mars goes wrong?', array['Gravity','The Martian','Interstellar','Ad Astra'], 1, 'medium'),
  ('Which TV series is narrated by a future version of the main character, Ted Mosby?', array['New Girl','How I Met Your Mother','Community','Scrubs'], 1, 'easy')
) as q(prompt, options, correct_index, difficulty)
where not exists (
  select 1 from public.questions existing where existing.prompt = q.prompt
);
