insert into public.questions (prompt, options, correct_index, category, difficulty)
select prompt, options, correct_index, 'Random Facts', difficulty
from (values
  ('How many sides does a stop sign have?', array['6','7','8','9'], 2, 'easy'),
  ('What is the most commonly used letter in the English alphabet?', array['A','E','S','T'], 1, 'medium'),
  ('How many bones does a shark''s skeleton contain?', array['0','50','100','200'], 0, 'hard'),
  ('What is the world''s most widely spoken native language?', array['English','Spanish','Mandarin Chinese','Hindi'], 2, 'medium'),
  ('How many time zones does mainland China officially use?', array['1','4','6','8'], 0, 'hard'),
  ('What was the first product ever sold with a barcode?', array['A pack of gum','A candy bar','A box of tea','A packet of cigarettes'], 1, 'hard'),
  ('How many humps does a Bactrian camel have?', array['1','2','3','0'], 1, 'easy'),
  ('What is the tallest type of grass in the world?', array['Wheat','Bamboo','Sugarcane','Elephant grass'], 1, 'medium'),
  ('Which country consumes the most coffee per capita?', array['Brazil','Finland','Italy','Colombia'], 1, 'hard'),
  ('What colour is a giraffe''s tongue?', array['Pink','White','Blue-black','Red'], 2, 'medium'),
  ('How many hearts does an earthworm have, functionally?', array['1','3','5','10'], 2, 'medium'),
  ('What is the only food that never spoils?', array['Rice','Honey','Salt','Sugar'], 1, 'medium'),
  ('How many teeth does an adult human typically have?', array['28','30','32','34'], 2, 'easy'),
  ('Which everyday object was originally called a "Kleenex" as a trademark for what item?', array['Napkins','Tissues','Paper towels','Toilet paper'], 1, 'easy'),
  ('What is the world''s most stolen food, according to police reports?', array['Chocolate','Cheese','Meat','Coffee'], 1, 'hard'),
  ('How many holes does a standard button typically have?', array['2','3','4','5'], 3, 'easy'),
  ('What is the term for a fear of long words?', array['Arachnophobia','Hippopotomonstrosesquippedaliophobia','Claustrophobia','Triskaidekaphobia'], 1, 'hard'),
  ('How many playing cards are in a standard deck, excluding jokers?', array['48','50','52','54'], 2, 'easy'),
  ('Which colour is traditionally associated with royalty and was historically expensive to produce?', array['Red','Purple','Gold','Blue'], 1, 'medium'),
  ('What is the most common blood type worldwide?', array['A positive','B positive','O positive','AB positive'], 2, 'medium'),
  ('How many red suits are there in a standard deck of cards?', array['1','2','3','4'], 1, 'easy'),
  ('What is a group of flamingos called?', array['A flamboyance','A flurry','A flock','A colony'], 0, 'hard'),
  ('How many degrees are there in a right angle?', array['45','90','180','360'], 1, 'easy'),
  ('What is the term for a word that reads the same forwards and backwards?', array['Anagram','Palindrome','Acronym','Homophone'], 1, 'medium'),
  ('Which fruit has its seeds on the outside rather than the inside?', array['Kiwi','Strawberry','Fig','Passionfruit'], 1, 'medium'),
  ('What is the term for a shape with five sides?', array['Hexagon','Pentagon','Heptagon','Octagon'], 1, 'easy'),
  ('How many letters are in the longest common English word without repeating any letter, "uncopyrightable"?', array['13','15','17','19'], 1, 'hard'),
  ('What is the standard number of dots on a single die?', array['1 to 6','1 to 8','1 to 5','1 to 10'], 0, 'easy'),
  ('Which is the only mammal that cannot jump?', array['Sloth','Elephant','Hippopotamus','Rhinoceros'], 1, 'hard'),
  ('What is the fear of Friday the 13th called?', array['Triskaidekaphobia','Paraskevidekatriaphobia','Arachnophobia','Nyctophobia'], 1, 'hard'),
  ('How many strings does a standard violin have?', array['3','4','5','6'], 1, 'easy'),
  ('What is the term for money paid to release a captive?', array['Bail','Ransom','Tribute','Alimony'], 1, 'easy'),
  ('Which is the only letter that does not appear in any US state name?', array['Q','X','Z','J'], 0, 'hard'),
  ('How many squares are there on a Rubik''s Cube face?', array['6','9','12','16'], 1, 'easy'),
  ('What is the term for a baby butterfly stage before it hatches?', array['Larva','Pupa','Caterpillar','Chrysalis'], 3, 'medium'),
  ('How many degrees Fahrenheit is normal human body temperature approximately?', array['96.6','98.6','100.6','102.6'], 1, 'easy'),
  ('What is the currency used in Japan?', array['Won','Yuan','Yen','Ringgit'], 2, 'easy'),
  ('What is the term for a word formed by rearranging the letters of another?', array['Palindrome','Anagram','Synonym','Homonym'], 1, 'medium'),
  ('How many zeros are in one million?', array['3','6','9','12'], 1, 'easy'),
  ('How many zeros are in one billion?', array['6','7','8','9'], 3, 'medium'),
  ('What is the world''s most populous city proper?', array['Tokyo','Shanghai','Chongqing','Mumbai'], 2, 'hard'),
  ('What is the standard number of squares on a chessboard, one colour?', array['16','32','48','64'], 1, 'medium'),
  ('What do you call a word that sounds the same as another but has a different meaning and spelling?', array['Synonym','Homophone','Antonym','Palindrome'], 1, 'medium'),
  ('What is the traditional gift for a 50th wedding anniversary?', array['Silver','Gold','Pearl','Ruby'], 1, 'easy'),
  ('What is the traditional gift for a 25th wedding anniversary?', array['Silver','Gold','Pearl','Diamond'], 0, 'easy'),
  ('How many minutes are there in a full 24-hour day?', array['1200','1440','1600','1800'], 1, 'medium'),
  ('What is the loudest a human sneeze has been recorded at, roughly comparable to which everyday sound?', array['A whisper','A vacuum cleaner','A jet engine at takeoff','Rustling leaves'], 1, 'hard'),
  ('What is the only sea in the world without any coastline, named for its floating algae?', array['The Dead Sea','The Sargasso Sea','The Coral Sea','The Caspian Sea'], 1, 'hard'),
  ('What is the collective name for a group of owls?', array['A murder','A parliament','A flock','A gaggle'], 1, 'medium'),
  ('What do you call a word that is its own opposite, like "dust"?', array['A contronym','A homograph','An oxymoron','A paradox'], 0, 'hard'),
  ('How many letters are there in the Hawaiian alphabet?', array['12','16','20','26'], 1, 'hard'),
  ('What is the world''s smallest country by area?', array['Monaco','Nauru','Vatican City','Tuvalu'], 2, 'medium'),
  ('What everyday item did Ruth Wakefield accidentally invent in 1938?', array['Popcorn','The chocolate chip cookie','Bubble gum','Cotton candy'], 1, 'medium'),
  ('How many hours are in a fortnight?', array['168','336','504','672'], 1, 'medium'),
  ('What is the maximum possible score for a single frame in ten-pin bowling with all strikes?', array['200','250','300','360'], 2, 'medium'),
  ('What colour do you get when you mix red and white paint?', array['Orange','Pink','Purple','Brown'], 1, 'easy'),
  ('What is the term for a polygon with eight sides?', array['Hexagon','Heptagon','Octagon','Nonagon'], 2, 'easy'),
  ('How many seconds are there in an hour?', array['600','1800','3600','7200'], 2, 'easy'),
  ('Which everyday material is made primarily from sand?', array['Plastic','Glass','Rubber','Ceramic'], 1, 'easy'),
  ('What is a "leap second" added to correct for?', array['Earth''s slowing rotation','Time zone drift','Daylight saving','Calendar errors'], 0, 'hard')
) as q(prompt, options, correct_index, difficulty)
where not exists (
  select 1 from public.questions existing where existing.prompt = q.prompt
);
